### PR TITLE
Feature/snowpack routes

### PR DESCRIPTION
**Pull request by npup**
## Changes

Make Astro's dev server intercept requests and route them according to any entries in the "routes" property of a snowpack configuration file - just like snowpack's own dev server.

## Testing

I did not write any tests for it yet since I wasn't sure how to do it in this test harness.

## Docs

No documentation updated yet.  I would think it would make sense to document which features are **not** picked up from snowpack configuration instead.  Most people seem to anticipate that they are honoured.

### CODE REVIEW

**Comment by jasikpark** [comment]
I'm uncertain this should be built into Astro, but it does sound nice! I feel like it'd be important to make it work for both `astro dev` and `astro preview` right?

**Comment by npup** [comment]
> I'm uncertain this should be built into Astro, but it does sound nice! I feel like it'd be important to make it work for both `astro dev` and `astro preview` right?

Absolutely, preview too now that you mention it. Thanks, I will look at that.

**Comment by tony-sull** [comment]
I'm not familiar with this RFC but it looks like it went from Needs Work to In Progress, was it already approved?

I definitely see the value here, especially if it's mainly bubbling up Snowpack config, but it feels a bit like throwing config-based routing back on top of the file-based routing approach

**Comment by npup** [comment]
> I'm not familiar with this RFC but it looks like it went from Needs Work to In Progress, was it already approved?
> 
> I definitely see the value here, especially if it's mainly bubbling up Snowpack config, but it feels a bit like throwing config-based routing back on top of the file-based routing approach

Hiya!

I'm not involved at all in the big plans and prioritisation etc., just trying to help with a feature I have heard quite a few users ask about (myself included, in June: https://github.com/snowpackjs/astro/issues/306)

The idea of this is definitely  just for use in development, so it is not meant to step on the toes of file based routing at all! - just makes it so that API calls for one's site can be routed in a convenient way. In production, those calls go to an nginx reverse proxy or something like that.  This is a killer feature of many other dev servers I have used, and I immediately missed it when I finally got Astro stuff up and running a while back (and it seems I was not alone).  

Snowpack does this beautifully on its own, so it seemed natural to me to bring that up from it's config, like several other features of it are reused for the greater good. :)

/p

**Comment by drwpow** [comment]
@npup thanks so much for this PR! I would normally try and help guide this to merge, but this is a special scenario where we are about to announce some changes to the dev server in Astro that this PR wouldn’t contribute toward. I would hate for you to put even more time into this for it to just change in a few weeks.

We’ll have something to announce in ~1 week that’ll make this cryptic message more clear, but just know that we will support more configurable routing in the very near future!

**Pull request closed without merging**
