### PR TITLE
🚀 Astro Next (0.21.0)

### PR DESCRIPTION
**Pull request by drwpow**
# 🚀 Astro Next (0.21.0)

Hello! This PR showcases a huge change to Astro, namely the new Go/WASM compiler, and switch to Vite. So this will work a little differently from most PRs. This will be a **long-running PR that other PRs get merged into** (no pushes directly, please!).

## 👀 For Viewers

If you’re using this to track the status of `astro@next--compiler`

### ✨ Try it today

⚠️ We recommend starting with a new project! Trying to use on an existing Astro project will likely not work until we have full feature parity.

```
npm install astro@next--compiler
```

### <a id="examples-linked">Examples Checklist - Complete, Linked</a>

Status: started

- [x]  **blog** (jn)
- [x]  **blog-multiple-authors** (dp)
- [x]  **docs** (jn)
- [x]  **framework-preact** (mp)
- [x]  **framework-react** (mp)
- [x]  **framework-svelte** (mp)
- [x]  **framework-vue** (mp)
- [x]  **framework-solid** (mp)
- [x]  **framework-lit** (mp)
- [x]  **framework-multiple** (mp)
- [x]  **minimal** (mp)
- [x]  **portfolio** (jn)
- [x]  **starter** (mp)
- [x]  **with-markdown** (nm)
- [x]  **with-markdown-plugins** (mp)
- [x]  **with-nanostores** (mp)

### <a id="examples-unlinked">Examples Checklist - Complete, Installed/Unlinked</a>

Status: finished

- [x] ***shared/general:** (mp) https://github.com/stackblitz/webcontainer-core/issues/335 (also: https://github.com/snowpackjs/astro/pull/1406#issuecomment-930506551)
- [x]  **blog** (jn)
- [x]  **blog-multiple-authors** (jn)
- [x]  **docs** (jn
- [x]  **framework-preact** (nm)
- [x]  **framework-react** (nm)
- [x]  **framework-svelte** (nm)
- [x]  **framework-vue** (nm)
- [x]  **framework-solid** (mp)
- [x]  **framework-lit** (mp)
- [x]  **framework-multiple** (dp)
- [x]  **minimal** (jn)
- [x]  **portfolio** (dp)
- [x]  **starter** (mp)
- [x]  **with-markdown** (dp)
- [x]  **with-markdown-plugins** (nm)
- [x]  **with-nanostores** (dp)

### 🧩 Stability

_Last updated: 2021-10-11_

- [ ] Enable Windows tests
- [x] Compiler needs scoping support for dynamic classes added in expressions https://github.com/snowpackjs/astro-compiler-next/pull/120
- [x] New features
    - [x] Define vars for script & style
    - [x] Astro components in Markdown
- [x] Frameworks
    - [x] Preact
    - [x] React
    - [x] Solid
    - [x] Svelte
    - [x] Vue
    - [x] Lit Element / Custom Elements
    - [x] slots in client components
- [x] API
    - [x] `Astro.fetchContent()` #1480 
    - [x] `Astro.resolve()` https://github.com/vitejs/vite/pull/5252
    - [x] `getStaticPaths()`
- [x] Markdown support
    - [x] Markdown plugins
- [x] Core features
    - [x] RSS
    - [x] Sitemap
    - [x] Scoped CSS
    - [x] Page-based routing
    - [x] Builtin Astro Components (Debug, Code, etc)
      - [x] Code #1635
      - [x] Debug #1633
      - [x] Markdown #1631
      - [x] Prism
    - [x] Top-level `fetch` in Astro pages
    - [x] Top-level `fetch` in Astro components
    - [x] Top-level `fetch` in any JS-like file
- [x] Integrations
    - [x] PostCSS
    - [x] Sass

## 🔧 For Contributors

For people helping move `astro@next--compiler` closer to stable release

### ✅ Contributing checklist

This `next` branch will act as a sort of `main` until it’s ready to merge. So in that sense, we’ll require the following workflow here:

- ✅ No commits directly to `main`. This should be enforced in GitHub.
- ✅ All contributions to `next` must be PRs targeted against this branch
- ✅ Your test suite must fully pass! (`npm run test` locally; ignore failing CI for now)

### ⏭ Moving to `main`

We’ll merge this PR into `main` when the **Stability** checklist above has been completed. Some items are intentionally left out, because they can be completed post-merge, with community involvement. This is including, but not limited to:

- [ ] CSS bundling
- [ ] Tailwind HMR
- [ ] client:only
- [x] Allow using scripts in `public/`
  - Works as expected if not used within a page.
  - If used within a page the build fails.
- [ ] Better `astro build` stats output
- [ ] Fine-tuned build optimizations
- [ ] Automatic `` and `srcset` inclusion
- [x] ~~Functional components in frontmatter~~
- [ ] Drop TSX/JSX support in frontmatter/compiler now that functional components not needed
- [ ] `getStaticPaths()` is no longer allowed to live further down the frontmatter
- [ ] Migration errors/warnings (if a user has Snowpack config, warn! if a user has old settings, warn! etc. etc.)
- [ ]  **with-tailwindcss** (mp)
    - Build: Styles are not built, because there is no HTML scanning during the build.
    - This is being added.

### CODE REVIEW

**Comment by brycewray** [comment]
**Bug report** re this PR.

I created a brand new project and installed with `npm install astro@next--compiler`. Set up the standard Astro directory structure as in the docs and put the "minimal" example's `index.astro` file in `./src/pages/`; also used the regular scripts from "minimal"'s `package.json`. On running `npm run dev`, I got the following output:

```bash
> astro-site@0.21.0 dev
> astro dev
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@astrojs/renderer-svelte' imported from /Users/thewrays/astro-site/node_modules/astro/dist/runtime/vite/config.jsError [ERR_MODULE_NOT_FOUND]: Cannot find package '@astrojs/renderer-svelte' imported from /Users/thewrays/astro-site/node_modules/astro/dist/runtime/vite/config.js
```

**Comment by brycewray** [comment]
Seeing the updates in the last few hours, I cleared out `node_modules`, `package-lock.json`, and `package-json` and started again with a fresh `npm init` followed by `npm install astro@next--compiler`. Resulting listing for Astro in `dependencies` in `package.json` is `"astro": "^0.0.0-compiler-202182123352"` — and when I run `npm run dev`, I get:

```bash
> astro-site@0.21.0 dev
> astro dev

 > node_modules/terser/dist/bundle.min.js:27827:39: error: Could not resolve "acorn" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
    27827 │                         return require("acorn").parse(files[name], {
          ╵                                        ~~~~~~~

Error: Build failed with 1 error:
node_modules/terser/dist/bundle.min.js:27827:39: error: Could not resolve "acorn" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
```

Sorry to be (again) the bearer of bad news.

**Comment by FredKSchott** [comment]
Very strange, @brycewray I can't reproduce on the `minimal` template!

"mark it as external" sounds like something coming from Astro or Vite, but then why would Terser be getting run within Astro?

**Comment by brycewray** [comment]
> Very strange, @brycewray I can't reproduce on the `minimal` template!
> 
> "mark it as external" sounds like something coming from Astro or Vite, but then why would Terser be getting run within Astro?

It is definitely weird. Hope there's an answer.

**Comment by borisv** [comment]
I tried now with all of the templates proposed via _npm init astro_ in separate clean installs. 

**Minimal** template seems to be the only one letting me do npm run dev. Serves and prints 200.

**Starter** template serves and throws 500:
`TypeError: Cannot read property 'ssr' of null
 at Module.renderComponent (../../src/internal/index.ts:188:33)`

**Portfolio** template quits and throws:
 `(node:15998) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
 at Function.entries (<anonymous>)
 at Module.renderComponent (/node_modules/astro/dist/internal/index.js:143:39)`

**Documentation** template quits and throws:
`> @example/docs@0.0.1 dev
> astro dev

 > src/components/Header/LanguageSelect.tsx:4:9: error: No matching export in "src/languages.ts" for import "KNOWN_LANGUAGES"
    4 │ import { KNOWN_LANGUAGES, langPathRegex } from '../../languages';
      ╵          ~~~~~~~~~~~~~~~

 > src/components/Header/LanguageSelect.tsx:4:26: error: No matching export in "src/languages.ts" for import "langPathRegex"
    4 │ import { KNOWN_LANGUAGES, langPathRegex } from '../../languages';
      ╵                           ~~~~~~~~~~~~~

Error: Build failed with 2 errors:
src/components/Header/LanguageSelect.tsx:4:9: error: No matching export in "src/languages.ts" for import "KNOWN_LANGUAGES"
src/components/Header/LanguageSelect.tsx:4:26: error: No matching export in "src/languages.ts" for import "langPathRegex"`

**Blog** template serves 500 and throws:

`500 Internal Error
/root/_DEV/astro.next/src/pages/index.astro: Expected ";" but found "STYLES"

  32 |       body {
> 33 |         width: 100%;
     |                                       ^
  34 |         display: grid;
  35 |         grid-template-rows: 3.5rem 1fr;
  36 |         --gutter: 0.5rem;`

Which is apparently unrelated to the source, since I can shift lines while the error stays on **33:39**

Where would be a proper place to post issues? I am bit shy of cluttering the issues tracker in main...

**Comment by brycewray** [comment]
Regarding the comment from @borisv . . .  I should note that I did **not** do `npm init astro` because I presumed that wouldn't be preferable with this particular version — or, to put it another way, that it would bring down different packages than you want with it.

**Comment by Olyno** [comment]
Using Starter + Svelte, I get a 500 error
```
/node_modules/astro/dist/internal/index.js:143
    for (const [key, value] of Object.entries(exported)) {
                                      ^

TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at Module.renderComponent (/node_modules/astro/dist/internal/index.js:143:39)
```

From [here](https://github.com/snowpackjs/astro/blob/next/packages/astro/src/internal/index.ts#L171)

**Comment by drwpow** [comment]
> Very strange, @brycewray I can't reproduce on the `minimal` template!

So what causes the error is the `renderers: []` on the minimal template (i.e. no renderers). Uncomment that line and you’ll see more errors. I’m still trying to investigate those, but have hit some weird behavior with Vite. But fix soon! 🙂

**Comment by brycewray** [comment]
> > Very strange, @brycewray I can't reproduce on the `minimal` template!
> 
> So what causes the error is the `renderers: []` on the minimal template (i.e. no renderers). Uncomment that line and you’ll see more errors. I’m still trying to investigate those, but have hit some weird behavior with Vite. But fix soon! 🙂

And, just to clarify: in my case (i.e., as opposed to that of @FredKSchott in his comment), all I used from the minimal template was its `index.astro` file. All else was a very basic install of `astro@next--compiler`.

**Comment by JosefJezek** [comment]
Lit 2 stable release is out. Please update Astro Lit Renderer.

https://github.com/snowpackjs/astro/blob/main/packages/renderers/renderer-lit/package.json

**Comment by JBTurtlin** [comment]
I can't get past this error when using the minimal starter and ```npm i astro@next-compiler```:

```sh
> @example/minimal@0.0.1 start
> astro dev

RangeError: Incorrect locale information provided
    at new DateTimeFormat (<anonymous>)
    at file:///home/michael/projects/astro_next/node_modules/astro/dist/logger.js:5:12
    at ModuleJob.run (internal/modules/esm/module_job.js:170:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
```

**Comment by obnoxiousnerd** [comment]
@JBTurtlin Fixed this in a new PR, please take a look: https://github.com/snowpackjs/astro/pull/1439

**Comment by Olyno** [comment]
Having an issue with the Svelte's render package when i go to ``localhost:3000``:

**Comment by Porges** [comment]
I gave this a try recently and noticed two things:
1. warnings that are logged by Vite do not seem to appear anywhere, even under `--verbose` mode
2. Vite always seems to be in `watch` mode, even during `astro build`. Is this intended?

**Comment by FredKSchott** [comment]
@brycewray I wasn't able to reproduce locally, but someone else was. Some additional details here to help triage/debug: https://github.com/stackblitz/webcontainer-core/issues/335#issuecomment-929630440

**Comment by obnoxiousnerd** [comment]
@Olyno I got the 500 error with this stack trace:
```
TypeError: Cannot read property 'ssr' of null
    at Module.renderComponent (../../src/internal/index.ts:187:33)
```
Which points to https://github.com/snowpackjs/astro/blob/5d7629ef1fba15e800202b8a4344684b049bccd1/packages/astro/src/internal/index.ts#L187
It is caused by something which is wrong with the markdown renderer

**Comment by matthewp** [comment]
I've just rebased this branch with main. I created a backup before, just in case: https://github.com/snowpackjs/astro/tree/next-backup-20210930

**Comment by brycewray** [comment]
@matthewp Upgraded to 202183012586 and still getting same error on `npm run dev` re `acorn` and `terser`. Just FYI.

**Comment by FredKSchott** [comment]
Played around with getStaticPaths and I saw it working in local dev and in build. However, the `pagination` test for it continues to fail. I traced the bug down to a compiler issue, where the Astro compiler result for `[page].astro` in the `pagination-test` fixture is:

```
import {
  render as $$render,
  createComponent as $$createComponent,
  renderComponent as $$renderComponent,
  renderSlot as $$renderSlot,
  addAttribute as $$addAttribute,
  spreadAttributes as $$spreadAttributes,
  defineStyleVars as $$defineStyleVars,
  defineScriptVars as $$defineScriptVars
} from "astro/internal";
export function getStaticPaths({paginate}) {

//@ts-ignore
const $$Component = $$createComponent(async ($$result, $$props, $$slots) => {
const Astro = $$result.createAstro($$props);
  const allPosts = Astro.fetchContent('../../post/*.md');

// ...
```

For some reason, `export function getStaticPaths({paginate}) {` gets hoisted up but the function body does not. Same thing happens for `export function getStaticPaths(c) {` as well. Notice the indentation weirdness as well.

**Comment by matthewp** [comment]
Just rebased with `main`, backup available at https://github.com/snowpackjs/astro/blob/next-backup-20211004/packages/astro/package.json

Relatively simple rebase so I wouldn't expect any problems; backup is there just in case.

**Comment by natemoo-re** [comment]
Just bumping with an update: Markdown is the big blocker for many of these examples but I've been working on getting it working again. Here's an upstream Vite PR that will unblock use of `remark` and friends, which should get the majority of our examples running again!

https://github.com/vitejs/vite/pull/5197

**Comment by matthewp** [comment]
@rhengles do you have a sample project you can share?

**Review by natemoo-re — APPROVED** [review]
:shipit:

**Pull request merged**
