### PR TITLE
Remove `prettier-plugin-astro` to fix Prettier CI

### PR DESCRIPTION
**Pull request by jasikpark**
## Changes 

Removes `prettier-plugin-astro`.

Prettier is currently hanging due to the `prettier-plugin-astro` directory. The Astro plugin causes an Out Of Memory error when run on embedded astro files.

<details>
<summary>Prettier Log</summary>
<pre>
<code>
✗  yarn format
yarn run v1.22.10
$ prettier -w "**/*.{js,jsx,ts,tsx,md,json}"
.changeset/config.json 704ms
.github/PULL_REQUEST_TEMPLATE.md 195ms
.prettierrc.json 15ms
.vscode/launch.json 110ms
.vscode/settings.json 8ms
.vscode/tasks.json 4ms
CODE_OF_CONDUCT.md 121ms
COMMUNITY.md 31ms
contributing.md 36ms
docs/blog/island-architecture.md 309ms
docs/core-concepts/astro-components.md 599ms
docs/core-concepts/astro-pages.md 123ms
docs/core-concepts/collections.md 174ms
docs/core-concepts/component-hydration.md 74ms
docs/core-concepts/layouts.md 338ms
docs/core-concepts/project-structure.md 68ms
docs/core-concepts/ui-renderers.md 168ms
docs/examples.md 30ms
docs/guides/data-fetching.md
<--- Last few GCs --->

[48885:0x7fd20e800000]   112180 ms: Scavenge 2041.8 (2075.1) -> 2040.8 (2075.1) MB, 3.0 / 0.0 ms  (average mu = 0.235, current mu = 0.249) allocation failure 
[48885:0x7fd20e800000]   112186 ms: Scavenge 2042.0 (2075.3) -> 2041.1 (2075.3) MB, 2.6 / 0.0 ms  (average mu = 0.235, current mu = 0.249) allocation failure 
[48885:0x7fd20e800000]   112192 ms: Scavenge 2042.3 (2075.6) -> 2041.3 (2075.6) MB, 1.7 / 0.0 ms  (average mu = 0.235, current mu = 0.249) allocation failure 

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x105152aea node::Abort() [/usr/local/Cellar/node/16.3.0/bin/node]
 2: 0x105152c69 node::OnFatalError(char const*, char const*) [/usr/local/Cellar/node/16.3.0/bin/node]
 3: 0x10528da85 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/Cellar/node/16.3.0/bin/node]
 4: 0x10528da2f v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/Cellar/node/16.3.0/bin/node]
 5: 0x1053e611d v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/Cellar/node/16.3.0/bin/node]
 6: 0x1053e8400 v8::internal::Heap::MarkCompactPrologue() [/usr/local/Cellar/node/16.3.0/bin/node]
 7: 0x1053e5e68 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/Cellar/node/16.3.0/bin/node]
 8: 0x1053e42a3 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/Cellar/node/16.3.0/bin/node]
 9: 0x1053e35c1 v8::internal::Heap::HandleGCRequest() [/usr/local/Cellar/node/16.3.0/bin/node]
10: 0x1053adf50 v8::internal::StackGuard::HandleInterrupts() [/usr/local/Cellar/node/16.3.0/bin/node]
11: 0x10562ba13 v8::internal::NativeRegExpMacroAssembler::CheckStackGuardState(v8::internal::Isolate*, int, v8::internal::RegExp::CallOrigin, unsigned long*, v8::internal::Code, unsigned long*, unsigned char const**, unsigned char const**) [/usr/local/Cellar/node/16.3.0/bin/node]
12: 0x10585d219 v8::internal::RegExpMacroAssemblerX64::CheckStackGuardState(unsigned long*, unsigned long, unsigned long) [/usr/local/Cellar/node/16.3.0/bin/node]
13: 0x144af4fc1c73 
14: 0x10562bc7f v8::internal::NativeRegExpMacroAssembler::Execute(v8::internal::String, int, unsigned char const*, unsigned char const*, int*, int, v8::internal::Isolate*, v8::internal::JSRegExp) [/usr/local/Cellar/node/16.3.0/bin/node]
15: 0x10562bbd0 v8::internal::NativeRegExpMacroAssembler::Match(v8::internal::Handle<v8::internal::JSRegExp>, v8::internal::Handle<v8::internal::String>, int*, int, int, v8::internal::Isolate*) [/usr/local/Cellar/node/16.3.0/bin/node]
16: 0x105633c39 v8::internal::RegExpImpl::IrregexpExecRaw(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSRegExp>, v8::internal::Handle<v8::internal::String>, int, int*, int) [/usr/local/Cellar/node/16.3.0/bin/node]
17: 0x105634300 v8::internal::RegExpGlobalCache::FetchNext() [/usr/local/Cellar/node/16.3.0/bin/node]
18: 0x105682202 v8::internal::Runtime_RegExpExecMultiple(int, unsigned long*, v8::internal::Isolate*) [/usr/local/Cellar/node/16.3.0/bin/node]
19: 0x105901a99 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/usr/local/Cellar/node/16.3.0/bin/node]
error Command failed with signal "SIGABRT".
</code>
</pre>
</details>

[exthost-c6414f.cpuprofile.txt](https://github.com/snowpackjs/astro/files/6773470/exthost-c6414f.cpuprofile.txt)
^^ VSCode output this from when I tried to format `astro/docs/guides/data-fetching.md`.

## Testing

N/A

## Docs

N/A

### CODE REVIEW

**Comment by jasikpark** [comment]
Probably the better solution though would be to move the prettier plugin into its own repo until it is finished, as @natemoo-re suggested, similar to how the docs in https://github.com/snowpackjs/astro-docs/ have been developed.

**Comment by jasikpark** [comment]
To see what will happen after this is resolved: see https://github.com/jasikpark/astro/files-that-needed-formatting

**Comment by jasikpark** [comment]
Nice! So hopefully https://github.com/snowpackjs/prettier-plugin-astro/ is up soon?

**Comment by natemoo-re** [comment]
> Nice! So hopefully https://github.com/snowpackjs/prettier-plugin-astro/ is up soon?

Working on that now, yep!

**Comment by natemoo-re** [comment]
Made a repo, will transfer over the existing code before merging https://github.com/snowpackjs/prettier-plugin-astro

**Comment by jasikpark** [comment]
Can you move #586 to the new repo?

**Comment by jasikpark** [comment]
https://github.com/snowpackjs/astro/blob/1bbe98ae54eb6018184fdc3875fe689775510ad6/package.json#L20 references to the prettier plugin might still need to be removed from `package.json`

**Pull request merged**
