### PR TITLE
Update www site

### PR DESCRIPTION
**Pull request by jonathantneal**
## Changes

This PR updates the `www` site to use Astro v0.21.

## Testing

manual testing the home page & blog (www fix only)

## Docs

www fix only

### CODE REVIEW

**Review by natemoo-re — APPROVED** [review]
Looks good to me!

**Review by jasikpark — APPROVED** [review]
lgtm! (is there a reason why all of the `woff` files got deleted?)

**Comment by jasikpark** [comment]
This PR is currently blocked by v0.21 not yet supporting building assets, for example the SCSS the www site uses!

**Comment by jonathantneal** [comment]
@jasikpark, https://caniuse.com/woff2

**Comment by jasikpark** [comment]
I think this PR can be merged + an additional PR can be opened if we need more improvements for 0.21 compact - it'd be good to test

image


in other branches w/ these fixes!

**Pull request merged**
