### PR TITLE
some docs site polish

### PR DESCRIPTION
**Pull request by FredKSchott**
- Doing this in prep to add search and upstream back into the `examples/docs` template

## Before

Screen Shot 2021-07-25 at 11 13 50 PM
Screen Shot 2021-07-25 at 11 13 46 PM

## After

Screen Shot 2021-07-25 at 11 13 30 PM
Screen Shot 2021-07-25 at 11 13 26 PM

### CODE REVIEW

**Comment by jasikpark** [comment]
Would it be possible to leave the theme switcher at the top? I feel like it makes sense to put it next to a search input and whatnot?

**Comment by aFuzzyBear** [comment]
Looks alot cleaner and polished, tbh im ambivalent about the location of the  theme switcher, having it down in its new location could open up space for the search bar in the header,

**Comment by matthewp** [comment]
Is the On this Page / More aside guaranteed not to be scrollable? If not then I think the switcher should go above those (whether in the site header or not I don't have an opinion). If not below is ok with me, but should be centered.

**Comment by FredKSchott** [comment]
> Looks alot cleaner and polished, tbh im ambivalent about the location of the theme switcher, having it down in its new location could open up space for the search bar in the header,

yup, this is exactly what I was thinking!



> Is the On this Page / More aside guaranteed not to be scrollable? If not then I think the switcher should go above those (whether in the site header or not I don't have an opinion). If not below is ok with me, but should be centered.

It's scrollable. I agree this might not be the perfect place for it, but I do think we should experiment with moving it out of the header. I'll try to play around with it a bit more after this before it settles in its final place. Also open to any other experimentation!

**Comment by jasikpark** [comment]
I've been wanting to make the right sidebar visible on mobile, though I'm not sure how we'd do that - honestly would just including it at the top of the page below the section title work? 

Details
  Summary = Table Of Contents
  <DocsSidebar>
    <ThemeToggle/>
  </DocsSidebar>


Something like that? So you can jump to the section you want on mobile, but we're not trying to do SiteSidebar mobile view part ii (i.e. a full screen modal)

**Comment by FredKSchott** [comment]
we used to do this on snowpack.dev and I liked it! Looks like it got reduced and looks a bit worse now, but you can still see it here on mobile: https://www.snowpack.dev/tutorials/quick-start

The trick is that you want it to show up under the title, but the sidebar is a separate block that can't get mixed into the article in between the page title and body. We did this on snowpack.dev by rendering two of them where we needed them, only showing one at a time via CSS. 

This may make sense for us as well, and would mainly require moving the "On this Page" `ul` out of `DocsSidebar` and into a second component that could be rendered to both places on the page.

**Comment by jasikpark** [comment]
> we used to do this on snowpack.dev and I liked it! Looks like it got reduced and looks a bit worse now, but you can still see it here on mobile: https://www.snowpack.dev/tutorials/quick-start
> 
> The trick is that you want it to show up under the title, but the sidebar is a separate block that can't get mixed into the article in between the page title and body. We did this on snowpack.dev by rendering two of them where we needed them, only showing one at a time via CSS.
> 
> This may make sense for us as well, and would mainly require moving the "On this Page" `ul` out of `DocsSidebar` and into a second component that could be rendered to both places on the page.

**Pull request merged**
