### PR TITLE
Fixed props shadowing

### PR DESCRIPTION
**Pull request by AsyncBanana**
This should fix the props shadowing mentioned in #1126. I don't think it will help after the Go compiler is made the default, but it should still help as of now.

# Changes

- Changes `props` names in two files to `$$props`

# Testing

- None

# Docs

- None

### CODE REVIEW

**Comment by jasikpark** [comment]
Looks like it's good to me - mind adding a test that tries to access the shadowed variable? It'd be nice to be sure that it's not accessible except through the `Astro` global

**Comment by AsyncBanana** [comment]
Thanks! I just added a test that checks for a failed response code because of accessing props without any other initialization.

**Comment by jasikpark** [comment]
Nice!

**Review by jasikpark — APPROVED** [review]
lgtm

**Comment by matthewp** [comment]
Perfect! Thank you!

**Pull request merged**
