### PR TITLE
Adding codesandbox config files to templates

### PR DESCRIPTION
**Pull request by aFuzzyBear**
## Changes

Adding codesandbox.io configuration file :  `sandbox.config.json` to the root of each template located in the `astro/examples/` directory. This is to enable codesandbox to deploy the correct sandbox enviroment when porting from github. Allowing their enviroment to work with Astro, so it can display the templates as online demonstrations. 
 This is the following configuration that is used. 
```json
{
    "infiniteLoopProtection": true,
    "hardReloadOnChange": false,
    "view": "browser",
    "template": "node",
    "container": {
      "port": 3000,
      "startScript": "start",
      "node": "14"
    }
}
```

### CODE REVIEW

**Comment by aFuzzyBear** [comment]
Like to give a lot of thanks to @sarah11918  for her help and lead on this, 
thank you very much buddy, I owe you a 🍺

**Comment by FredKSchott** [comment]
Thanks @aFuzzyBear! I think we're going to wait a few more days to see if https://github.com/codesandbox/codesandbox-importers/pull/138 gets merged, but if it does not then we'll merge this PR!

**Comment by aFuzzyBear** [comment]
Awesome dude, ill hold off on this, it will only be a case of adding in the links to the package.json, ill have the rest hooked up and a pr of the examples page read for you hopefully in the next couple of days dude,

**Comment by matthewp** [comment]
codesandbox/codesandbox-importers#138 was merged, does this mean that this PR is not needed now?

**Pull request closed without merging**
