### PR TITLE
Make link and imgs build relative to the site

### LINKED ISSUE #380: HTML file is not generated when leading slash is missing in css path
## Problem
When I run `npm run build` no .html files are generated, but also no errors in console appear.

## How to reproduce:
1. Run `npm init astro`
2. Run `npm install`
3. Replace the content of `src/pages/index.astro` with `<link rel="stylesheet" type="text/css" href="style/global.css">`
4. Run `npm run build`
5. Result: No index.html being built (and also no errors in log, see below)

<details>
<summary>Show log</summary>
> @astrojs/starter-kit@0.0.1 build
> astro build

[config] Set "buildOptions.site" to generate correct canonical URLs and sitemap
[15:42:26] [snowpack] Welcome to Snowpack! Because this is your first time running
this project, Snowpack needs to prepare your dependencies. This is a one-time step
and the results will be cached for the lifetime of your project. Please wait...
[15:42:27] [snowpack] + @astrojs/renderer-vue/server@0.1.1
[15:42:27] [snowpack] └── vue@3.1.1
[15:42:27] [snowpack]   └── @vue/runtime-dom@3.1.1
[15:42:27] [snowpack]     └── @vue/runtime-core@3.1.1
[15:42:29] [snowpack]       └── @vue/reactivity@3.1.1
[15:42:30] [snowpack]         └── @vue/shared@3.1.1
[15:42:30] [snowpack]       └── @vue/shared@3.1.1 (dedupe)
[15:42:30] [snowpack]     └── @vue/shared@3.1.1 (dedupe)
[15:42:30] [snowpack] + @astrojs/renderer-vue/client@0.1.1
[15:42:30] [snowpack] └── vue@3.1.1 (dedupe)
[15:42:30] [snowpack]   └── @vue/runtime-dom@3.1.1 (dedupe)
[15:42:30] [snowpack]     └── @vue/runtime-core@3.1.1 (dedupe)
[15:42:30] [snowpack]       └── @vue/reactivity@3.1.1 (dedupe)
[15:42:30] [snowpack]         └── @vue/shared@3.1.1 (dedupe)
[15:42:30] [snowpack]       └── @vue/shared@3.1.1 (dedupe)
[15:42:30] [snowpack]     └── @vue/shared@3.1.1 (dedupe)
[15:42:30] [snowpack] + @astrojs/renderer-svelte/server@0.1.0
[15:42:30] [snowpack] └── svelte/internal@3.38.2 (dedupe)
[15:42:31] [snowpack] + @astrojs/renderer-svelte/client@0.1.0
[15:42:31] [snowpack] + @astrojs/renderer-svelte/client@0.1.0 (ssr)
[15:42:32] [snowpack] └── svelte/internal@3.38.2 (dedupe)
[15:42:32] [snowpack] + @astrojs/renderer-react/server@0.1.0
[15:42:32] [snowpack] └── react@17.0.2
[15:42:32] [snowpack]   └── object-assign@4.1.1
[15:42:32] [snowpack] └── react-dom/server.js@17.0.2
[15:42:33] [snowpack]   └── object-assign@4.1.1 (dedupe)
[15:42:33] [snowpack]   └── react@17.0.2 (dedupe)
[15:42:33] [snowpack]     └── object-assign@4.1.1 (dedupe)
[15:42:33] [snowpack] + @astrojs/renderer-react/client@0.1.0
[15:42:33] [snowpack] └── react@17.0.2 (dedupe)
[15:42:33] [snowpack]   └── object-assign@4.1.1 (dedupe)
[15:42:33] [snowpack] └── react-dom@17.0.2
[15:42:34] [snowpack]   └── react@17.0.2 (dedupe)
[15:42:34] [snowpack]     └── object-assign@4.1.1 (dedupe)
[15:42:34] [snowpack]   └── object-assign@4.1.1 (dedupe)
[15:42:34] [snowpack]   └── scheduler@0.20.2
[15:42:34] [snowpack] + @astrojs/renderer-preact/server@0.1.0
[15:42:34] [snowpack] └── preact@10.5.13
[15:42:35] [snowpack] └── preact-render-to-string@5.1.19
[15:42:35] [snowpack]   └── preact@10.5.13 (dedupe)
[15:42:35] [snowpack] + @astrojs/renderer-preact/client@0.1.0
[15:42:35] [snowpack] └── preact@10.5.13 (dedupe)
[15:42:35] [snowpack] + astro/dist/internal/h.js@0.12.10
[15:42:35] [snowpack] + astro/components/Prism.astro@0.12.10
[15:42:35] [snowpack] └── @astrojs/prism@0.2.0
[15:42:36] [snowpack] └── prismjs@1.23.0
[15:42:36] [snowpack] + svelte-hmr/runtime/hot-api-esm.js@0.13.5
[15:42:36] [snowpack] └── svelte/internal@3.38.2 (dedupe)
[15:42:36] [snowpack] + svelte-hmr/runtime/proxy-adapter-dom.js@0.13.5
[15:42:36] [snowpack] + astro/components@0.12.10
[15:42:37] [snowpack] └── @astrojs/prism@0.2.0 (dedupe)
[15:42:37] [snowpack] └── prismjs@1.23.0 (dedupe)
[15:42:37] [snowpack] Ready!
[build] ! building pages...
[build] ✔ pages built.
[build] ! optimizing css...
[build] ✔ css optimized.
[build] ! copying public folder...
[build] ✔ public folder copied.
[build] ! bundling...

   Pages                                                     Page Weight (GZip)  
[build] ▶ Build Complete!
</details>

## How to fix
Add the missing slash in step 3: `<link rel="stylesheet" type="text/css" href="/style/global.css">`

<details>
<summary>Show log</summary>
> @astrojs/starter-kit@0.0.1 build
> astro build

[config] Set "buildOptions.site" to generate correct canonical URLs and sitemap
[15:48:09] [snowpack] Ready!
[build] ! building pages...
[build] ✔ pages built.
[build] ! optimizing css...
[build] ✔ css optimized.
[build] ! copying public folder...
[build] ✔ public folder copied.
[build] ! bundling...

   Pages                                                     Page Weight (GZip)  
 ┌ /index.html                                               0.00 kB             
[build] ▶ Build Complete!
</details>

## Intended behaviour
I am actually not sure what the intended behaviour should be. Either it should throw an error in the console or maybe it should work without the slash too 🤷‍♂️.

The weird thing is that it works in develop mode.

### PR DESCRIPTION
**Pull request by matthewp**
Fixes #380

## Changes

This makes it when non-absolute URLs are used for link and img tags that they are resolved relative to `buildOptions.site`, rather than the file system. I don't think we intentionally wanted relative links to resolve to the src file in these cases at least.

## Testing

Added a test.

## Docs

N/A

### CODE REVIEW

**Comment by natemoo-re** [comment]
I think this is a step in the right direction, but this is a huge of a can of worms... Maybe we should expose a function to handle this? Something like `Astro.getOutputPath`? That way users would explicitly use it wherever they need to, rather than Astro playing whack-a-mole with every possible edge case here.
- What if the user has a `<base>` element?
- What about ``? 
- What about image lazy-loading? Pretty typical to use `lazysizes` with `data-src`.

**Comment by matthewp** [comment]
@natemoo-re I think we need to talk about this before merging this change. The core question is how should relative paths in HTML be resolved? In HTML they would be resolved relative to the `baseURI`, which is what this PR does. But some (in the past) have asked about making it relative to the file you're currently in.

I'm not certain which is the right choice, but either I think we need to pick one of those and then make it be consistent on all elements (this PR doesn't touch scripts for example). And then provide some utility like you suggest for when you want to resolve another way.

**Comment by FredKSchott** [comment]
Not sure I totally follow the fix here. Are we talking about what happens when you use a relative path in something like an Astro component?

If something feels like a footgun we can prevent you from doing it. For ex: a relative `img src` inside of a component feels broken no matter what we do. Could we fix this with a warning instead? something like:

```
<img src="foo.jpg" />       # Warning at build-time, maybe even error
```
```
<img src="/foo.jpg" />       # Good
```
```
---
import imgUrl from './foo.jpg';
---
<img src="{imgUrl}" />       # Good, uses absolute URL
```

**Comment by matthewp** [comment]
Going to close as I do think this needs a bit more discussion.

**Pull request closed without merging**
