### PR TITLE
fix middleware order to prevent HMR issues

### PR DESCRIPTION
**Pull request by FredKSchott**
## Changes
- Vite middleware can tackle HMR webhooks and exact asset references before our router
- Vite assets are always more specific than our user routes, which means they should run first to prevent getting caught by a super flexible route like `/*`
- Fixes that issue where HMR events get reported as `/` routing errors in the console

## Testing
- Covered by existing tests (actual behavior shouldn't have been impacted, but dev server should run faster and not log as many false errors)

## Docs
- N/A

### CODE REVIEW

**Review by natemoo-re — APPROVED** [review]
LGTM!

I think the reasoning here was that we might want to intercept something _before_ Vite, but I agree with the problems motivating this change.

**Comment by matthewp** [comment]
Would love @drwpow to take a look since he knows more of the context of going before.

**Comment by FredKSchott** [comment]
this was something that @drwpow  and I had discussed a while back and I believe they were +1 on, but agreed will wait for their feedback/review.

**Review by drwpow — APPROVED** [review]
I think we talked about this and this works for me! Won’t cause any issues that I’m aware of.

**Pull request merged**
