### PR TITLE
(next) Redesigned 404 page

### PR DESCRIPTION
**Pull request by mcfadyeni**
Added Astro logo, updated layout, and changed colors.

## Changes

- Redesigned the 404 page on Not Found errors.

## Testing

- Design change only, no code changed.

## Docs

- No docs updated.

### CODE REVIEW

**Comment by mcfadyeni** [comment]
Updating CSS since there's some overflow on the edges (scrolling) when there shouldn't be.

**Comment by drwpow** [comment]
Absolutely love this! A great improvement. Screenshot for other people:

Screen Shot 2021-11-12 at 08 43 13

**Review by drwpow — APPROVED** [review]
Looks great! No feedback. Thank you!

**Comment by drwpow** [comment]
Ah, shoot! I didn’t notice the merge target was `next`; we’re on `main` now. Will cherry-pick.

**Comment by mcfadyeni** [comment]
> Ah, shoot! I didn’t notice the merge target was `next`; we’re on `main` now. Will cherry-pick.

Whoops, sorry!

**Comment by drwpow** [comment]
Re-opened here: https://github.com/snowpackjs/astro/pull/1811

**Comment by drwpow** [comment]
Would love your feedback on the changes!

**Pull request merged**
