### PR TITLE
fix: add force to rm script in create-astro

### PR DESCRIPTION
**Pull request by BryanPan342**
## Changes

Fix the remove script to use `--force` to emulate a `rm -rf` to clear subdirectories during `create-astro`. I think this is a valid solution because the create script asks if it can override the files, but fails on subdirectories. 

What **would** be nice would be to save the `.git` directory and such. But not sure if that should be included in this PR.

## Testing

Not sure how to perform testing because all the current testing is on templates. I also don't mind adding a section later in the test that is run under the fixtures directory.

## Docs

Bug fix?

Fixes: #

### CODE REVIEW

**Comment by BryanPan342** [comment]
This change probably has some unforeseen consequences with stuff like `.vscode`, `.git`, etc. But I will leave it up to the maintainers to decide what's the best way of handling this error.

Worse comes to worst, we can always just have a better error message! Or just only delete the files and not the directories.

**Comment by FredKSchott** [comment]
Your change is more in line with the behavior that we intended here. However, the problem here is the user message: we don't really tell you that we're going to remove files. Can you update the message to be more clear what the user is about to confirm? Something like:

```diff
-        message: 'Directory not empty. Continue?',
+        message: `Directory not empty. Delete ${cwd} to continue?`,
```

**Comment by BryanPan342** [comment]
@FredKSchott Updated the text to match the behavior. I also did more testing and found out that the original implementation cannot work due to the fact that `rm` does not take in `.` or `..` as a valid argument. So instead I created an `emptyDir` function.

**Review by FredKSchott — APPROVED** [review]
LGTM! Appreciate the change

**Pull request merged**
