### PR TITLE
Remove check for referenced files

### LINKED ISSUE #757: 🐛 BUG: Build fails when referencing "public" javascript files.
### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug
(Astro version 0.19.1)

Build fails when importing a javascript file from "./public" directory.

Note: this works properly on the dev server -- just not when building for production.
Note: importing CSS files in the same way does not cause a similar issue.

### Steps to Reproduce

1. Init generic astro project
2. Run `npm install`
3. Add basic javascript file at /public/index.js
4. Add basic astro html file at /src/pages/indes.astro that references the above javascript file.
5. Run `npm run build`
6. Error! Build fails with message 'Error: file:///.../src/pages/index.astro: could not find "index.js"
   at file:///.../node_modules/astro/src/build.ts:140:25'
7. Run `npm start`
8. Visit http://localhost:3000/
9. Open console. Note the javascript file has bee pulled in to /src/pages/index.astro.

### Link to Minimal Reproducible Example (Optional)

https://github.com/johnhenry/astro-build-fail-imports

### PR DESCRIPTION
**Pull request by johnhenry**
## Changes

Resolves #757.

Fixes issue in which build process necessarily checked for existence of files
and errored-out if they did not exist. 

## Testing

Added a test in `packages/astro/test/astro-ext-ref.test.js`

## Docs

bug fix only

### CODE REVIEW

**Comment by matthewp** [comment]
Hi @johnhenry, thanks for raising this issue, but I'm unclear on what the bug is here. It seems like the file *does* exist, so why is it erroring?

**Comment by johnhenry** [comment]
@matthewp Currently when building, the application analyzes script tags within a .astro file and throws an error if a referenced file does not exist. This is simply part of the HTML and should not prevent a build (whether it exists or not).

Also, this behavior is not consistent with the development server which serves the HTML generated from the .astro file.

This PR fixes that by displaying a waring rather than throwing an error -- allowing the build to continue.

I have removed `public/index.js` from the test fixture to make it clear that the existence of the referenced file should not affect the build.

**Comment by matthewp** [comment]
This fixes #1122

**Comment by FredKSchott** [comment]
LGTM, rebased, cleaned up a bit, and merged with passing tests in d771dad66990f6436472b6ed185261da45be13f0

Thanks @johnhenry !

**Pull request closed without merging**
