### PR TITLE
Improved JSX framework detection

### PR DESCRIPTION
**Pull request by matthewp**
## Changes

This improves the JSX detection and adds a bunch of test. The following is improved:

* If an error throws because of a coding mistake, those errors will be reported.
* We properly detect class components for both Preact and React. We don't have to "try to render" these.

It's still possible that error messages might be obscured in this scenario:

A Preact function component that uses hooks (or another preact specific feature) that has a coding mistake. The React renderer might throw when it uses the Preact hook. That error will be reported rather than the real coding mistake.

This is because we can't distinguish between errors that are due to the wrong framework and errors that the user caused.

I might reach out to the Preact community and see if they can think of a better solution to this problem. This will come up when other JSX based frameworks have renderers. I still think that having multiple frameworks in the same project is a feature worth trying to preserve.

## Testing

- [✅] Tests are passing
- [✅] Tests updated where necessary

## Docs

N/A

### CODE REVIEW

**Review by drwpow — APPROVED** [review]
🎉

**Comment by drwpow** [comment]
> I still think that having multiple frameworks in the same project is a feature worth trying to preserve.

+100 to this. And I think Preact and React are very likely cohabitants of the same project, especially if someone is trying to migrate from React to Preact, for example.

**Comment by FredKSchott** [comment]
+1 as well. I still want to have a convo about the best way to deliver on that though. (Maybe `.react.jsx`, maybe a `/// astro.renderer=react` at the top of the file, etc. etc.) but this is a great step forward regardless

**Review by FredKSchott — APPROVED** [review]

**Comment by matthewp** [comment]
Realized I can probably move the try/catch out of the renderer, simplifying it's signature. So I want to make that change before merging this.

**Pull request merged**
