### PR TITLE
Add test for copying over dotfiles from `/public` + try to update the…

### LINKED ISSUE #689: 🐛 BUG: empty dotfiles in public directory not moved to dist directory
### What package manager are you using?

npm/yarn

### What operating system are you using?

Windows/Ubuntu/MacOSX

### Describe the Bug

Empty dotfiles such as `.nojekyll` (required for Github Pages hosting due to `_`-prepended directories in dist) are not moved from the public directory as part of `astro build`.

### Steps to Reproduce

1. have an astro project
2. add an empty dotfile like `.nojekyll` to `public/`
3. `astro build`
5. Empty dotfile is not moved to `dist/` directory

### Link to Minimal Reproducible Example (Optional)

https://github.com/bloodyaugust/greyson-site

### PR DESCRIPTION
**Pull request by jasikpark**
… config to work

## Changes

- Updates the snowpack mounting of `/public` to enable dotfile support

## Testing

Added a test to `astro-public.test.js` that checks whether `.nojekyll` and `.htaccess` get copied over on build.

Currently the test fails because only `.nojekyll` gets copied over???

## Docs

bug fix only ~ fixes #689

### CODE REVIEW

**Comment by jasikpark** [comment]
Looks like the Snowpack tests don't test for this case of having more than one dotfile 😅

https://github.com/snowpackjs/snowpack/blob/4ab4f07e2f355ca4884c6aa48faec40a07e2318a/test/snowpack/config/mount/index.test.js#L236-L277

**Comment by jasikpark** [comment]
Looks like the regex is fine... https://regex101.com/r/qrwGy2/1

**Comment by FredKSchott** [comment]
This should be fixed by the larger work coming out next week with the compiler! Normally I'd merge this anyway, but in this case I'm a bit worried about introducing new bugs accidentally. Would be better to focus our efforts there!

**Comment by jasikpark** [comment]
I think I'll just rewrite it as a "adds a failing testcase" only pr so we're at least tracking it

**Comment by FredKSchott** [comment]
That would be great! Nate and drew are making a new PR of their work which already has failing tests, so if you can rebase it off of that branch (once they've created it) then we should be okay to merge in the failing tests without having to skip it.

Obviously, would also love a fix to that branch as well :)

**Pull request closed without merging**
