### PR TITLE
Use accessible indentation

### PR DESCRIPTION
**Pull request by jonathantneal**
## Changes

This changes the examples in Astro to use tabs, the currently most accessible indentation. It also happens to align the indentations of all examples, which currently use a mix of "four-space" , "two-space", and "tab" indentation.

> Just had a conversation about indentation with a blind programmer, and realized this is the most accessible indentation convention as well. Tabs as indentation means # tabs = indent level, and all spaces (including alignment spaces) can be simply ignored when reading out code.
> — [@fantasai](https://twitter.com/fantasai/status/1039647453618659328) (W3C CSSWG specifications writer, 2004 to present)

This change isn’t just for blindness. As devices improve and developers age, we’re seeing new preferences develop that necessitate dynamic indentation; something currently only possible with tabs. For example:

- Jane Developer uses a tab width of 1 because they use a large font size.
- Jill Developer uses a tab width of 8 because they use a very wide monitor.

I am also a developer who either struggles reading capturing two-space indentation at a comfortable font size, or struggles capturing the meaning of uncomfortably large text at a comfortable indentation. By supporting dynamic indentation, we can enable developers to choose the indentation that makes the most sense for them.

I’m making no claims that any one indentation size is superior, or even that no size is superior. I’m only asking for this preference because I enjoy coding and require dynamic indentation to code comfortably at length; and I believe I am hardly alone in requiring this. If at some future point browser and IDE developers can change how space-indentation is announced and can enable space indentation to stretch or contract — this could be changed to any other preference your team desires.

## Testing

No tests are needed, because this is not a functional change to the project.

## Docs

No doc changes are needed, because this only affects examples.

### CODE REVIEW

**Comment by MarcusOtter** [comment]
Personally I'm a big +1 on this. I just recently (VERY recently, a few weeks ago) started using tabs over spaces for these reasons you mentioned as well. Makes total sense to me, just one downside is that GitHub and some other popular services where this code will be shown has 1 tab = 8 spaces by default which can look offputting if people don't have any extensions that change this (most IDEs and text editors default to 2 or 4 spaces afaik).

Wonder if this could be applied to the entire codebase?

**Comment by FredKSchott** [comment]
I've been waiting for the day I'd be pulled into a "tabs vs. spaces" discussion, I just can't believe that @jonathantneal was the person to do it!

I'm generally +1 to this change and its objective argument, and anything that has to do with making our codebase more accessible to more people.

If we can though, I'd like to make this change in our `prettier` config file and then just run `yarn format` on the entire codebase. Otherwise, this PR will get reverted by our autoformatter the second that it gets merged :)

To do that, i think we need to wait for the new compiler work to get merged back in, since I would hate to think what this would do to those merge conflicts.

**Review by FredKSchott — COMMENTED** [review]
I've been waiting for the day I'd be pulled into a "tabs vs. spaces" discussion, I just can't believe that @jonathantneal was the person to do it!

I'm generally +1 to this change and its objective argument, and anything that has to do with making our codebase more accessible to more people.

I would, however, like to make this change in our prettier config file and then just run yarn format on the entire codebase. Otherwise, this PR will get reverted by our autoformatter the second that it gets merged :) This would mean converting astro/src, tests, and the rest of the project to tabs as well.

To do that, i think we need to wait for the new compiler work to get merged back in, since I would hate to think what this would do to those merge conflicts.

**Comment by jasikpark** [comment]
> I've been waiting for the day I'd be pulled into a "tabs vs. spaces" discussion, I just can't believe that @jonathantneal was the person to do it!
> 
> I'm generally +1 to this change and its objective argument, and anything that has to do with making our codebase more accessible to more people.
> 
> I would, however, like to make this change in our prettier config file and then just run yarn format on the entire codebase. Otherwise, this PR will get reverted by our autoformatter the second that it gets merged :) This would mean converting astro/src, tests, and the rest of the project to tabs as well.
> 
> To do that, i think we need to wait for the new compiler work to get merged back in, since I would hate to think what this would do to those merge conflicts.

I suppose it'd also be an edit to `.editorconfig` as well, right?

**Comment by eyelidlessness** [comment]
I want to add a more vocal +1 on this, and say that I’m glad to see this gaining some traction. I’ve preferred tabs over spaces as long as I’ve been coding, but it’s always felt like a losing battle.

I wrote a thread about this recently: https://twitter.com/eyelidlessness/status/1426037036025212928?s=21

> I had no idea I was arguing this when I tried to advocate for tabs in the past, but I didn’t know a lot of things about my brain and thought I was just being fussy. Turns out I have different indentation preferences depending on my cognitive abilities at that time.

I will add one caution: big formatting changes tend to make navigating git history more difficult. Which is also an accessibility issue (i.e. the added cognitive load can be challenging for those of us with cognitive difficulties already). Regardless of if/when this lands, I wanted to raise that in case folks have ideas/want to consider ways to mitigate that.

**Comment by jasikpark** [comment]
A solution for large formatting changes can be a git revisions file, which removes a commit from consideration when looking at `git blame` https://www.moxio.com/blog/43/ignoring-bulk-change-commits-with-git-blame

**Comment by FredKSchott** [comment]
@jasikpark that's awesome, TIL! 

I'm going to close this PR because it's already out of date and we have no plans to merge in the next few days. But, when/if this change is approved and prioritized the PR should just be a one-line change to our `.prettierrc` file.

**Comment by jasikpark** [comment]
> @jasikpark that's awesome, TIL!
> 
> I'm going to close this PR because it's already out of date and we have no plans to merge in the next few days. But, when/if this change is approved and prioritized the PR should just be a one-line change to our `.prettierrc` file.

(and a change to https://github.com/snowpackjs/astro/blob/main/.editorconfig#L7

**Pull request closed without merging**
