### PR TITLE
Add repository remotes for all astro packages

### PR DESCRIPTION
**Pull request by jasikpark**
## Changes

- What does this change?
- Be short and concise. Bullet points can help!
- Before/after screenshots can be helpful as well.

Adds the git remote URL for each package to their respective package.json's so that services like renovatebot and dependabot can find them.

### CODE REVIEW

**Review by FredKSchott — DISMISSED** [review]
I think you need to do this format for npm, etc. to pick up the repo + the subdirectory:

```
// example from snowpack monorepo
// https://www.npmjs.com/package/@snowpack/plugin-vue
  "repository": {
    "type": "git",
    "url": "https://github.com/snowpackjs/snowpack.git",
    "directory": "plugins/plugin-vue"
  },
```

**Comment by jasikpark** [comment]
@FredKSchott that makes sense to me! Do you have a link to documentation for why that's the right config btw? I was searching for it and I ended up doing the same and browsing GitHub repos for examples. Some other repos have just the full URL to the package, where others just have a link to the base repo. I'll update my PR to reflect those changes since that makes the most sense syntax-wise to me though.

**Comment by jasikpark** [comment]
https://github.com/renovatebot/renovate/issues/4724 it seems that nested packages are a bit iffy? I'll have to investigate more...

**Comment by jasikpark** [comment]
https://docs.npmjs.com/files/package.json
image
we do have documentation of whether that's the right syntax there tho xD

**Comment by jasikpark** [comment]
It looks like renovatebot is having problems with detecting nested changelogs in a monorepo: https://github.com/renovatebot/renovate/issues/2926

**Comment by jasikpark** [comment]
https://github.com/jasikpark/my-astro-project/pull/9 whoop! It finally works after renovatebot fixed their issues!

**Pull request merged**
