### PR TITLE
Add algolia-powered search bar to docs site

### PR DESCRIPTION
**Pull request by FredKSchott**
## Changes

- Add Algolia-powered search bar to header
- [X] place search bar correctly on mobile
- [x]  get docsearch properly scanning our site: https://github.com/algolia/docsearch-configs/pull/4413

### CODE REVIEW

**Comment by jasikpark** [comment]
Should this work once the new version is published?

**Comment by FredKSchott** [comment]
It should work now since the site builds with the local version of Astro

**Comment by jasikpark** [comment]
hmmm well vercel hasn't seemed to deploy it yet 😬

**Comment by jasikpark** [comment]
image

It does look like the mobile styles need to be sorted + the actual data hooked up to search rather than the tailwind docs

**Comment by FredKSchott** [comment]
mobile styles updated!

**Comment by jasikpark** [comment]
> mobile styles updated!

looks good! Maybe there could be more even margin on the left and right side of the Astro logo on mobile? flex-grow the search bar?

Also maybe add padding to the keyboard shorcut box so that it has a `1:1` aspect ratio?

**Comment by FredKSchott** [comment]
great ideas! Will do both tonight. And then my contact at Algolia got back and said they could get us set up tomorrow, so if all goes well this should be good to merge tomorrow!

**Comment by jasikpark** [comment]
btw, why did you change from CMD+K? That seems to be a pretty popular command shortcut for quick-nav for example in the Tailwindcss Docs, in Discord you can quickly search for a switch between channels via CMD+K, and in Linear, an issue tracking app they use it for quick commands..

'/' is also a great option, I'm just a bit biased 😆

**Comment by FredKSchott** [comment]
Ah, love that `client:idle` isn't affecting our site perf for the new search bar! https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fastro-docs-git-wip-search-bar-pikapkg.vercel.app%2Fgetting-started

**Comment by jasikpark** [comment]
image
oops this is a problem - without this fix the sites we link to via `target="_blank"` can access the page that opened it

**Comment by FredKSchott** [comment]
Got a response from the algolia team. Index was added, code updated to use the new api key, but now seeing an odd permissions error. Following up with them in that PR.

**Comment by FredKSchott** [comment]
It lives! Just waiting for vercel to update

**Comment by FredKSchott** [comment]
Will merge this later today unless anyone reports an issue

**Pull request merged**
