### PR TITLE
silence vercel comments in PR

### PR DESCRIPTION
**Pull request by FredKSchott**
## Changes

- This comment is super noisy, imo, since most changes don't impact docs or www
- you can still view any preview from the CI "checks" list that's built into GitHub

## Testing

- If there is no comment on this PR, we were successful!

### CODE REVIEW

**Comment by jasikpark** [comment]
Clicking on the vercel checks takes me to a page to log into vercel :/ it doesn't seem to work..

It would be nice to be able to keep the comments but just mute the notifications, but I don't think Github has that in their bot api

**Comment by FredKSchott** [comment]
ah shoot nevermind, the "Details" link takes you to the deployment page and not the actual preview URL. Anyone who isn't me would see a "log in" page 🤦  oh well, was a good idea!

**Comment by jasikpark** [comment]
https://github.com/vercel/vercel/issues/3166 this might be topical

**Comment by FredKSchott** [comment]
That feature actually exists! We can ignore based on a bash command / script returning an exit code of 0 or 1.

I actually had it ignoring everything outside of `docs/` and `www/` (respectively) but then realized that we were using "did that site build and work" as a way to test some PRs, so I removed it. I don't think that was a dealbreaker though, and I could add it back!

Alt: create a CI test that builds the www & docs sites so that we still get that testing confidence without forcing vercel to do it.

**Comment by jasikpark** [comment]
yeah, I think adding a CI test is a good idea, since we should still test whether the sites build in PR's that don't touch those folders, for example the Version Packages PRs - maybe we could have two CI tests: one for building docs&www and one for building all projects under the examples directory?

**Comment by FredKSchott** [comment]
+1, running build on all examples + www + docs and just checking for errors would be a great start. Then in the future, we could keep improving and test the actual output itself against some expected snapshot, visual snapshot testing, etc.

If you have any interest in building that, that would be great! It could be written using `uvu` like our other tests, or just be a single Node.js script that throws when `yarn build` fails on any project. `execa` is our recommended library for running commands from Node, you can see some examples of it for this kind of integration test in the snowpack repo.

**Pull request closed without merging**
