### PR TITLE
fix styling guide

### PR DESCRIPTION
**Pull request by rubensdemelo**
fix styling guide

## Changes

- What does this change?
- Be short and concise. Bullet points can help!
- Before/after screenshots can be helpful as well.

### CODE REVIEW

**Review by jasikpark — CHANGES_REQUESTED** [review]
Can you actually just delete the "/docs" and leave it as a relative URL? I think that's how the other pages link to each other, which lets us navigate to other pages on preview deploys

**Review by jasikpark — APPROVED** [review]
LGTM!

**Comment by jasikpark** [comment]
🙃 wait a second from the PR title I thought you were updating the docs, not an example repo README: you should definitely use the full url, sorry

**Review by FredKSchott — APPROVED** [review]
Thank you!

**Comment by FredKSchott** [comment]
Lol @jasikpark I did the same thing! In reality, this should link to the docs website now and not a local markdown file. I'll make that change now. Thanks for catching

**Pull request merged**
