### PR TITLE
Update lit version to v2

### PR DESCRIPTION
**Pull request by stramel**
## Changes

Bumps to the official v2 release of Lit and the official v1 release of @lit-labs/ssr in the lit renderer

## Testing

Tests are passing

## Docs

Shouldn't need any documentation update.

### CODE REVIEW

**Comment by matthewp** [comment]
Thanks! It looks like it's having trouble accessing `document`: https://github.com/snowpackjs/astro/pull/1445/checks?check_run_id=3724759035#step:9:404

The Lit renderer installs Lit's window shim on the global so it *should* be there: https://github.com/snowpackjs/astro/blob/main/packages/renderers/renderer-lit/server-shim.js#L1

Might need to debug why we are getting this error.

**Comment by stramel** [comment]
@matthewp Seems all the errors stem from an update to `@lit-labs/ssr`. Everything passed with Lit v2 update by itself

**Comment by stramel** [comment]
I'm able to remove the shim completely since the lit-element-renderer handles rendering with the shim. the only test that fails after doing so is the rendering a custom element by tag name in the lit element test. Everything else passes successfully. 

It appears the window isn't getting reset to the original after this shim is applied globally.

**Comment by matthewp** [comment]
Thanks for the research @stramel! 

I don't think that those other tests need the shim, but rather that the existence of the shim causes their code to branch (due to some feature detection I imagine). So this is kind of a good thing, because it's catching "what happens when you have Lit & React/etc. in the same project).

I'm fine with adding the `window.global` if that's all it takes.

**Pull request merged**
