### PR TITLE
Use normalized path to detect layout files

### PR DESCRIPTION
**Pull request by bencemol**
## Changes

- Fixes layouts being rendered as fragments on non-unix environments

## Testing

Tested on Windows 10, using the [astro blog starter](https://github.com/snowpackjs/astro/tree/main/examples/blog)

## Docs

No changes

### CODE REVIEW

**Review by jasikpark — APPROVED** [review]
lgtm, though i don't *entirely* understand what's going on, i assume this has to do with how the "layout" key in markdown works on Windows?

**Comment by matthewp** [comment]
If you rebase with `main` this should pass again now.

**Comment by bencemol** [comment]
> lgtm, though i don't _entirely_ understand what's going on, i assume this has to do with how the "layout" key in markdown works on Windows?

Yes, `id` contains unix style slashes on windows, so `isPage` was set to false for layouts.

**Review by jonathantneal — APPROVED** [review]
Looks good! Thanks for the explanation in the thread.

**Pull request merged**
