### PR TITLE
Docs: Add zh-tw translation for Setup

### PR DESCRIPTION
**Pull request by ymcheung**
## Changes
- Add `zh-TW` folder in docs/src/pages

`zh-Hant-TW` Translation:
- [x] Get Started
- [x] Quick Start
- [x] Installation 
- [x] Examples
- [ ] Astro vs. X 

## Testing
N/A

## Docs
This is the translation update for Docs

### CODE REVIEW

**Comment by FredKSchott** [comment]
Thank you for contributing! @ChelesteWang submitted https://github.com/snowpackjs/astro/pull/979 right before you, which also includes `zh-cn`. Instead of merging this PR, could you help review their translation instead and provide any feedback/edits?

**Comment by ymcheung** [comment]
> Thank you for contributing! @ChelesteWang submitted #979 right before you, which also includes `zh-cn`. Instead of merging this PR, could you help review their translation instead and provide any feedback/edits?

Sure! There are some terms and grammar differences between `zh-tw` and `zh-cn`.
So I will take a look at `zh-tw` translation in that PR.

**Comment by ChelesteWang** [comment]
@ymcheung We can translate together

**Comment by ymcheung** [comment]
@FredKSchott I will continue the zh-tw translations in this PR.
I noticed that the value of `lang` attribute in `<html>` for Traditional Chinese should be `zh-hant-TW`.
```
<html lang="zh-hant-TW" class="initial">
```
Therefore, I have updated the folder name and the settings.

**Comment by FredKSchott** [comment]
@ChelesteWang can you help review? I do not know the language so I can't review myself :)

**Comment by jasikpark** [comment]
Maybe it'd be helpful to use https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl rather than raw strings for the i18n lang codes?

**Comment by ymcheung** [comment]
> I believe that it should still be `zh-TW`. This is my first time seeing `zh-hant-TW` and i'm worried that it will break our region code parsing in `src/pages/index.astro`. Can you share a link with more information about why `zh-hant-TW` is needed? Otherwise, lets keep `zh-TW` for now.

Sorry! It should be `zh-Hant-TW` actually.

`zh-Hant-TW` is referred from the ISO standard:
https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry

Wikipedia also uses this for Traditional Chinese pages:
https://zh.wikipedia.org/zh-tw/ISO_639-3
CleanShot 2021-08-05 at 16 01 30@2x
but `zh-tw` for the route :D

**Comment by ChelesteWang** [comment]
@ymcheung @FredKSchott The following comes from Tags for Identifying Languages
zh-Hans Simplified Chinese
zh-Hans-CN Simplified Chinese used in mainland China
zh-Hans-HK Simplified Chinese used in Hong Kong
zh-Hans-MO Simplified Chinese used in Macau
zh-Hans-SG Simplified Chinese used in Singapore
zh-Hans-TW Simplified Chinese used in Taiwan
zh-Hant Traditional Chinese
zh-Hant-CN Traditional Chinese used in mainland China
zh-Hant-HK Traditional Chinese used in Hong Kong
zh-Hant-MO Traditional Chinese used in Macau
zh-Hant-SG Traditional Chinese used in Singapore
zh-Hant-TW Traditional Chinese used in Taiwan

**Comment by ChelesteWang** [comment]
zh-hans and zh-hant can be used directly if there is no more translation about Chinese，Of course, the specification of translation is not the same，For example Vue and Angular use CN & TW ，React use hans & hant

**Comment by FredKSchott** [comment]
@ymcheung @ChelesteWang  okay thank you for confirming! This looks good to me then! 

@ymcheung is this ready to merge?

**Comment by ChelesteWang** [comment]
> @ymcheung @ChelesteWang okay thank you for confirming! This looks good to me then!
> 
> @ymcheung is this ready to merge?

How about unifying them into zh-hans and zh-hant
@FredKSchott @ymcheung

**Comment by ymcheung** [comment]
> @ymcheung is this ready to merge?

@FredKSchott I find "Astro vs. X" will take some time to translate. Other sections in Setup are ready to go!

**Comment by FredKSchott** [comment]
> > @ymcheung is this ready to merge?
> 
> @FredKSchott I find "Astro vs. X" will take some time to translate. Other sections in Setup are ready to go!

No problem, you should skip that one for now. We were really only looking for the "getting started" page, so you have done even more which is great! 

By next week, the "BASICS" section should be finished and ready to translate. If you are able to, we'd love your help on them when it's ready. Thank you!

**Pull request merged**
