### PR TITLE
Adds support for client:media hydrator

### LINKED ISSUE #396: 💡 RFC: Support partial hydration based on custom media queries
@matthewp and @natemoo-re brought up some ideas related to this in Discord, opening this issue for discussion

The basic idea is to only hydrate custom JS on the client based on a media query, along the lines of

`<MobileMenu:media query="screen and (max-width: 768px)" />`

This would also add feature detection support via media queries level 4, think `@media (hover: hover)` to only load a component that supports hover input

### PR DESCRIPTION
**Pull request by matthewp**
Closes #396 and #514

Demo: https://www.loom.com/share/c7ffe9467ce445ee946c40583ef06b63

## Changes

This adds support for `client:media`. The value passed to the attribute gets passed through the hydration metadata. It's not passed as a string so that references to scope values will be picked up. This is tested.

## Testing

Added tests both for static values and using a scope variable. 

## Docs

Docs updated.

### CODE REVIEW

**Review by jasikpark — COMMENTED** [review]
This looks awesome!

**Comment by jasikpark** [comment]
I like this workflow idea which is basically the same as the example, but a little prettier to me:

```tsx
---
import { Component }  from "./Component.tsx";
import { media } from "./media.js";
// or`import { lg } from "./media.js";` as in the PR example
---
<Component client:media="{media.lg}"/>
 ```
```ts
// in media.js
export const media = {
  lg: "(min-width: 700px)",
  ...
};
export const lg = media.lg;
```

**Comment by jasikpark** [comment]
In a bikeshedding-comment, could this be combined with the other directives? 🤔 Since this is orthogonal in a way to the other directives -- `client:visible:media={MOBILE}` seems a bit complicated but also powerful, in tune with how Tailwind works with media directives.

**Comment by matthewp** [comment]
@jasikpark like could you combine this with `visible` and whichever happens first wins? If so, no, only 1 hydrator runs. Maybe something for the future.

**Review by natemoo-re — APPROVED** [review]
Looks great! Really excited about this feature!

**Comment by jasikpark** [comment]
> @jasikpark like could you combine this with `visible` and whichever happens first wins? If so, no, only 1 hydrator runs. Maybe something for the future.

Exactly. It'd definitely a feature for the future, not something that should block getting this out, but I would definitely say it's useful since currently `client:media` functions as `client:load:media` atm.

**Comment by matthewp** [comment]
> Exactly. It'd definitely a feature for the future, not something that should block getting this out, but I would definitely say it's useful since currently client:media functions as client:load:media atm.

Not exactly, `client:load` loads the code when the browser finishes loading. media loads it only when/if a media query matches.

**Comment by matthewp** [comment]
Merging, please continue the conversation :)

**Comment by jasikpark** [comment]
> > Exactly. It'd definitely a feature for the future, not something that should block getting this out, but I would definitely say it's useful since currently client:media functions as client:load:media atm.
> 
> Not exactly, `client:load` loads the code when the browser finishes loading. media loads it only when/if a media query matches.

When does it load then? If you load the page initially with the correct screen size, when would the component load?

**Pull request merged**
