### PR TITLE
Support PureComponent in the react renderer

### LINKED ISSUE #1400: 🐛 BUG: React.PureComponent not supported from top-level
### What package manager are you using?

npm

### What operating system are you using?

Mac (catalina)

### Describe the Bug

When rendering a react component from an astro page, it does not recognize that the react renderer will work, throwing the error:

```
Error: No renderer found for StaticComponent! Did you forget to add a renderer to your Astro config?
```

It works if I make the component inherit from `React.Component` rather than `React.PureComponent`, or if I have a wrapper component that does so and simply renders the original component. 

Presumably, in checking which render to use, it checks if a component inherits from React.Component but not React.PureComponent. I'd be happy to make this my first PR if someone can point me toward a file to look at!

### Steps to Reproduce

A simple example is as follows. In `page.astro`:
```
---
import StaticComponent from '../components/static_component.jsx';

---

<body>
<StaticComponent />
</body>
```

The component looks like:
```
import React from 'react';

export default class StaticComponent extends React.PureComponent {

    render() {
        return (
            <div>
                <h1>Static component</h1>
            </div>
        )
    }

}
```

### Link to Minimal Reproducible Example (Optional)

_No response_

### PR DESCRIPTION
**Pull request by matthewp**
## Changes

- The React Renderer now is able to detect Pure components as being React components.
- Closes #1400

## Testing

Test added

## Docs

Bug fix only

### CODE REVIEW

**Review by jasikpark — APPROVED** [review]
lgtm! is this a bug in the preact renderer as well with preact pure components i wonder?

**Comment by matthewp** [comment]
Preact doesn't have a PureComponent.

**Comment by jasikpark** [comment]
> Preact doesn't have a PureComponent. Thanks for the review!

it does in 'preact/compat'!: https://preactjs.com/guide/v10/switching-to-preact#purecomponent

**Comment by matthewp** [comment]
I see, our detection should already be working: https://github.com/preactjs/preact/blob/master/compat/src/PureComponent.js#L10

Feel free to add a test though

**Pull request merged**
