### PR TITLE
Upstream `astro-docs` into `examples/docs`

### PR DESCRIPTION
**Pull request by okikio**
## Changes
fix `editHref` bug in `Main.astro` by adding this,
```ts
const editHref = githubEditUrl;
```
just below `githubEditUrl`, fixing the bug without any major issues.

## Testing

I tested this in an example repo, https://github.com/okikio/astro-build

[Open In Gitpod](https://gitpod.io/#https://github.com/okikio/astro-build)

## Docs

No, docs required, its a bug fix, with no major changes added

### CODE REVIEW

**Comment by jasikpark** [comment]
Could you actually yoink the updated code from the https://github.com/snowpackjs/astro-docs repo? We really need to upstream some of our changes that we've made in that repo to this example!

**Comment by okikio** [comment]
Would you like me to make the blog example basically a clone of astro-docs?

**Comment by jasikpark** [comment]
> Would you like me to make the docs example basically a clone of astro-docs?

That's basically what I was thinking, though definitely keep it a simple docs example! maybe don't copy over the AvatarList calling out to Github? Idk..

**Comment by okikio** [comment]
Ok, I'll get right on that

**Comment by FredKSchott** [comment]
This might be a bit trickier than it sounds! Feel free to give it a try, otherwise I can help out tomorrow

**Comment by FredKSchott** [comment]
for context: now that the public docs site is near complete, the goal is to move that website back into this repo at the `/docs` directory. So what @jasikpark is requesting here is pretty much spot on.

**Comment by okikio** [comment]
The current pull request has been updated with `astro-docs` files, but I still need to fix a couple more bugs before we can merge it

**Comment by FredKSchott** [comment]
Done!

**Comment by okikio** [comment]
@FredKSchott did you already fix the bugs in `astro-docs`?

**Comment by jasikpark** [comment]
@FredKSchott this PR is not about pulling the astro-docs repo into the main repo, but updating the docs starter in `examples/docs` with the improvements we've made to astro-docs.

**Comment by okikio** [comment]
@jasikpark Thanks

**Comment by okikio** [comment]
@FredKSchott I'm still working to fix the bugs in the docs example, and I have updated the docs example to use the astro docs design

**Comment by FredKSchott** [comment]
didn't mean to close. However, I think @natemoo-re is doing some larger work next week to turn this template into something more component-based so that projects could depend on it like a package. So I'd definitely reach out to @natemoo-re if you're still interested in working on this, possibly with him!

**Comment by FredKSchott** [comment]
Closing this in favor of @natemoo-re's component-based upstreaming. I'm trying to do some work this week to help prepare the way for that

**Pull request closed without merging**
