### PR TITLE
Adds a new example template portfolio-svelte

### PR DESCRIPTION
**Pull request by delight**
- Template is based on svelte components instead of react

## Changes

- Adds an aditonal template portfolio-svelte, that is based on svelte components. Would be nice to have an example template that is not react.

## Testing

1) did the yarn build and yarn test steps 
2) ran `yarn dev` on the mai project + `yarn dev` on the template. Everything worked as expected

## Docs

No, I didn't see any section about adding docs for templates

### CODE REVIEW

**Comment by matthewp** [comment]
Thanks @delight, can you rebase this branch please? Thank you.

**Comment by delight** [comment]
> Thanks @delight, can you rebase this branch please? Thank you.

Done :+1:

**Comment by delight** [comment]
@matthewp just bumped astro dep to "^0.21.0-next.0" for portfolio-svelte template

**Comment by matthewp** [comment]
Great, thank you!

**Pull request merged**
