### PR TITLE
Upgrade to snowpack@3.8.0

### PR DESCRIPTION
**Pull request by matthewp**
## Changes

This fixes a script execution ordering bug.

## Testing

Tested in snowpack.

## Docs

N/A, bug fix.

### CODE REVIEW

**Comment by natemoo-re** [comment]
@matthewp any clue why these tests are failing?

**Comment by matthewp** [comment]
@natemoo-re not exactly but snowpack@3.8.0 has some issues that broke astro so we had to pin to 3.7.1. I think we might need to bring bundling back into snowpack for the time being, let's discuss offline.

**Comment by matthewp** [comment]
The reason for the tests failing is related to this Yarn bug: https://github.com/yarnpkg/yarn/issues/4513 Basically it seems like dependencies are some times not installed in the root? Weird, but manually installing in the root as devDeps does fix it for me.

**Review by natemoo-re — COMMENTED** [review]
Weird that those Astro deps need to be hoisted... I can see that being a problem if they get out of sync.

Other than that, LGTM!

**Review by FredKSchott — APPROVED** [review]
LGTM! This should definitely get a `pre`/`next` release (at least for 1-2 days) to test before going out to everyone, just given how subtle a change this

**Pull request merged**
