### PR TITLE
Fix `<script hoist src={Astro.resolve()}/>` not resolving. 

### LINKED ISSUE #1320: 🐛 BUG: Hoisted scripts do not evaluate `src` expression
### What package manager are you using?

npm, yarn

### What operating system are you using?

macOS

### Describe the Bug

Hoisted external scripts don't work as described [in the docs](https://docs.astro.build/core-concepts/astro-components#hoisted-scripts):

```jsx
<script src={Astro.resolve('./my-component.js')} hoist></script>
```

The compiler does not evaluate expressions passed to a hoisted script `src`, it will instead process it as a bare string:

https://github.com/snowpackjs/astro/blob/e686c3c50469d18db93da7ce79ddcac8659c3166/packages/astro/src/compiler/codegen/index.ts#L678-L680

This behavior has not been caught because it's currently not covered by [the according test](https://github.com/snowpackjs/astro/blob/e686c3c50469d18db93da7ce79ddcac8659c3166/packages/astro/test/astro-scripts.test.js#L12-L21).

### Steps to Reproduce

1. `npm init astro` using the "minimal" template
2. Create a `main.js`:

   ```sh
   echo 'console.log("hello world") > src/main.js'
   ```
3. Insert `<script src={Astro.resolve('../js/main.js')} hoist></script>` somewhere into the `src/pages/index.astro`.

   ```sh
   sed -i '' 's|<body>|<body>\n\t<script src={Astro.resolve("../js/main.js")} hoist></script>|' src/pages/index.astro
   ```
4. Build project.

   ```sh
   npm run build
   ```
5. The build failed, because it could not find a script with the path `/Astro.resolve(...`. As per the docs, the expression should be properly resolved instead.

   ```
   [build] Could not load /Astro.resolve( (imported by astro-virtual:/index.js): ENOENT: no such file or directory, open '/Astro.resolve('
   npm ERR! code ELIFECYCLE
   npm ERR! errno 1
   npm ERR! @example/minimal@0.0.1 build: `astro build`
   npm ERR! Exit status 1
   npm ERR!
   npm ERR! Failed at the @example/minimal@0.0.1 build script.
   npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
   
   npm ERR! A complete log of this run can be found in:
   npm ERR!     /Users/florian/.npm/_logs/2021-09-05T17_34_33_343Z-debug.log
   ```

### Link to Minimal Reproducible Example (Optional)

_No response_

### PR DESCRIPTION
**Pull request by jasikpark**
## Changes

- Fixes #1320

## Testing

Added a failing test to `astro-scripts.test.js` 

maybe it should be in `astro-globals.test.js` and `astro-globals-build.test.js`?

## Docs

bug fix only

### CODE REVIEW

**Comment by FredKSchott** [comment]
Nice find! We don't normally merge failing tests, so can you either:

1. turn this into a `.skip` test, and then we can merge it for someone else to come along and fix (with a comment in #1322 
2. fix the issue as a part of this PR.

**Comment by jasikpark** [comment]
I'm hoping I can fix it in this PR!

**Comment by FredKSchott** [comment]
Closing as not fixed, but will leave the branch around for anyone else to pick up and work on!

**Comment by jasikpark** [comment]
I'm realizing I might want to have separate "adds failing test" and "fixes said test" pr's 😅

**Pull request closed without merging**
