### PR TITLE
Add `.gitpod.yml` for continuous prebuilds for speedy project startup!

### PR DESCRIPTION
**Pull request by jasikpark**
## Changes

- Adds `.gitpod.yml` with start tasks for continuous prebuild: https://www.gitpod.io/docs/config-start-tasks

### CODE REVIEW

**Comment by FredKSchott** [comment]
I'm a soft -1 on anything specific to any 3rd-party tool making it into the repo, where we'll also have to consider adding config files for codesandbox, stackblitz, github codespaces, repl.it, glitch, etc. etc.

If we could select 1-2 to be "officially" supported online code editors, and write that down somewhere in contributing.md, and then not merge any other config files, then I could be +1 on this.

**Review by FredKSchott — CHANGES_REQUESTED** [review]
I'm a soft -1 on config files specific to any 3rd-party tool making it into the repo, where we'll also have to consider adding config files for codesandbox, stackblitz, github codespaces, repl.it, glitch, etc. etc.

If we could select 1-2 to be "officially" supported online code editors, and write that down somewhere in contributing.md, and then not merge any other config files, then I could be +1 on this.

**Comment by jasikpark** [comment]
> I'm a soft -1 on config files specific to any 3rd-party tool making it into the repo, where we'll also have to consider adding config files for codesandbox, stackblitz, github codespaces, repl.it, glitch, etc. etc.
> 
> If we could select 1-2 to be "officially" supported online code editors, and write that down somewhere in contributing.md, and then not merge any other config files, then I could be +1 on this.

right, this is more of a case of a config for enabling contributing to the repo, rather than a codesandbox.config.js added to an `examples` directory.

**Comment by FredKSchott** [comment]
Yup, my point is more that your repo can become a mess of one-off config files that get added once and then never maintained. 

My personal preference would be to agree to something like this as a team: "The Astro repo officially supports remote development via GitHub Codespaces (github.dev), and we will maintain any config that is needed in the repo to make this as easy as possible. Any other remote dev environments are still available to you as a contributor, so you are free to pick your favorite, but the repo will not officially maintain configuration for any other remote dev environments / editors."

**Comment by jasikpark** [comment]
> Yup, my point is more that your repo can become a mess of one-off config files that get added once and then never maintained.
> 
> My personal preference would be to agree to something like this as a team: "The Astro repo officially supports remote development via GitHub Codespaces (github.dev), and we will maintain any config that is needed in the repo to make this as easy as possible. Any other remote dev environments are still available to you as a contributor, so you are free to pick your favorite, but the repo will not officially maintain configuration for any other remote dev environments / editors."

That sounds reasonable to me! I would argue for https://gitpod.io due to their large free tier for open-source + their tier that gives you unlimited hours for maintainers of open-source projects, whereas Github Codespaces is only open to people who got into the private beta, Teams, and Enterprise Teams.

**Comment by FredKSchott** [comment]
Oh, is that still true? I thought that github.dev was public now: For ex can anyone not access this? https://github.dev/snowpackjs/astro

If that's not correct then yes, +1 or GitPod or similar

**Comment by jasikpark** [comment]
> Oh, is that still true? I thought that github.dev was public now: For ex can anyone not access this? [github.dev/snowpackjs/astro](https://github.dev/snowpackjs/astro)
> 
> If that's not correct then yes, +1 or GitPod or similar

So https://gihub.dev is generally available, but it is just a nice editing UI for github, rather than the feature-to-feature alternative to gitpod that github codespaces is! you only get an editor and vscode extensions, while in gitpod.io you can compile your own Linux distros if you want to!

**Comment by FredKSchott** [comment]
Ah, gotcha. I hadn't realized that difference. +1 for adding GitPod for now then, I know others have talked about how great it is in the Discord. I'd also love to evaluate Stackblitz given how unique it is but that can come later.

**Review by FredKSchott — APPROVED** [review]
LGTM

**Pull request merged**
