### PR TITLE
remove optional chaining from built package

### PR DESCRIPTION
**Pull request by FredKSchott**
## Changes

- Fixes astro runtime issue on <v14
- I believe regression was introduced in #304, but not positive

### CODE REVIEW

**Comment by jasikpark** [comment]
Could this also include a fix for the node v12 tests faultily passing?

**Review by jasikpark — APPROVED** [review]

**Comment by FredKSchott** [comment]
oh jeeze, we're not testing Node 12! Will add a fix for that here.

**Review by jasikpark — APPROVED** [review]

**Review by jasikpark — APPROVED** [review]

**Comment by jasikpark** [comment]
Glad I asked about the node 12 testing 😆

**Review by jasikpark — APPROVED** [review]

**Comment by FredKSchott** [comment]
turns out quite a few things were not working in v12! I think most of this was only affecting the `next` release, luckily. But yea, very surprised that the lack of node v12 tests had gone unnoticed given our declared support for it.

**Pull request merged**
