### PR TITLE
docs: added 2 pages in French

### PR DESCRIPTION
**Pull request by GauBen**
## Changes

The French documentation has never been this big! 😄 

## Testing

Hmm, not sure how to test markdown. Maybe add https://github.com/markdownlint/markdownlint in the future?

## Docs

Oui, en effet.

### CODE REVIEW

**Comment by jasikpark** [comment]
That looks great! The docs don't need added testing in the same sense a feature of code == tests, but it might be a good idea to add a `yarn workspace docs lint` github action 🤔

**Comment by GauBen** [comment]
Random ideas for doc linting:
- Markdownlint
- [Words To Avoid in Educational Writing](https://css-tricks.com/words-avoid-educational-writing/)
- Prettier for markdown
- [Make sure that code blocks are syntactically correct](https://github.com/eslint/eslint-plugin-markdown)

**Comment by jasikpark** [comment]
You can check Prettier off that list :) We've already got that going

**Comment by jasikpark** [comment]
Those definitely all seem pretty solid :)

**Pull request merged**
