### PR TITLE
Provide completion suggestions in component props

### PR DESCRIPTION
**Pull request by matthewp**
Closes https://github.com/snowpackjs/astro/issues/1021

Loom: https://www.loom.com/share/3e513a5a97e64446acf9d2af80d41e36

## Changes

Updates the Astro plugin in the vscode extension to provide prop suggestions on components that export a `Props` interface.

### CODE REVIEW

**Comment by FredKSchott** [comment]
This is great! Love seeming these PRs/looms.

I assume showing a red squiggly error if you provide the wrong type for a prop (or don't include a required prop) is a separate, follow-up task?

Also, I saw how the "autocomplete" dropdown showed every possible HTMLElement attribute. But my understanding is that its up to the component author to opt-in to apply those props to the template: `<div {...otherProps}>`. If they don't do that, the prop is never applied. Usually, the components that I write (and see our community write) only read from the props that I explicitly define in `interface Props`.

Can we make this opt-in as well, via something like this?

```
export interface Props {
  // explicit, only these props are supported
}

// or...

export interface Props extends HTMLElement {
  // explicit, I am telling the consumer that I pass my ...props to the element correctly
}
```

Another benefit here is that this lets you choose what type of element you're extending, so that you could extend something like a button (HTMLButtonElement) or a select dropdown (HTMLSelectElement) and extend the correct props.

**Comment by matthewp** [comment]
Good point able HTML attribute autocompletes, I think the answer is to just remove that, because you're right that those aren't properties of the component (unless they define them).

Yes, errors is another issue, #1020

**Comment by matthewp** [comment]
Fixed that, loom: https://www.loom.com/share/cfe326058e6746df99a011d366723208

**Review by natemoo-re — APPROVED** [review]
✅ This is wonderful!

Regarding extending prop types, we should include _some_ type definition that makes it easy to extend specific elements and enable polymorphism. That can be a separate PR!

**Comment by FredKSchott** [comment]
> Regarding extending prop types, we should include _some_ type definition that makes it easy to extend specific elements and enable polymorphism. That can be a separate PR!

I *think* HTMLElement and friends are included as globals in TS by default? Otherwise, maybe you need to add the `dom` lib. But it seemed to work out of the box in Matthew's loom!

**Comment by natemoo-re** [comment]
@FredKSchott It _worked_ but it wasn't doing what you'd expect. If you notice it was offering completions based on the DOM interface of `HTMLElement` (so things like `tagName`, `getBoundingClientRect()`, etc).

This would be some TypeScript shenanigans like the ones React is using. https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1349b640d4d07f40aa7c1c6931f18e3fbf667f3a/types/react/index.d.ts#L1342

**Comment by matthewp** [comment]
Can you create another issue on this @natemoo-re ? I'm not sure what this is doing that you didn't expect but happy to talk about it and fix later

**Pull request merged**
