### PR TITLE
Update astro-pages.md: Create custom 404 error page

### PR DESCRIPTION
**Pull request by pointout**
## Changes

Added info how to create a custom 404 error page

### CODE REVIEW

**Review by jasikpark — APPROVED** [review]
Looks great! Mind specifying that it will create a `/404.html` page specifically so that services like Netlify can find it - which is different than the default behavior for pages which generate `/[slug]/index.html` rather than `/[slug].html` like the 404 page :)

**Comment by pointout** [comment]
> 
> 
> Looks great! Mind specifying that it will create a `/404.html` page specifically so that services like Netlify can find it - which is different than the default behavior for pages which generate `/[slug]/index.html` rather than `/[slug].html` like the 404 page :)

good point. extended the text.

**Review by jasikpark — APPROVED** [review]
lgtm :)

**Comment by FredKSchott** [comment]
LGTM! Thanks for the clarification!

**Pull request merged**
