### PR TITLE
Docs/example and templates v2

### PR DESCRIPTION
**Pull request by aFuzzyBear**
This PR is a continuation of PR: #871 .

After taking Fred's comments onboard. This is my attempt at a second pass on developing the Examples page.

Here I have setup a function that would collate the data found within the `examples/ [template] ` package.json and its corresponding Readme file. This then form the basis of the content that would be displayed to the user. 

This is just a WIP, to get some early doors feedback to see if this is progressing in the right direction

My Intentions moving forward:
1) Add and Enrich the content within the examples/pkgJson and Readme files, this would then be upstreamed into the new pages, on build*. But the idea is update the files and would reflect with the docs site. (I've made a separate note to the end of this PR to setup/lookup a github action to automate this so if the examples repo is update, it would trigger a build of the docs site) 
2) Once I have better content to work with, I was looking to revisit the `example` page and re-structure it better. 
3) Add a Sidebar for external links to see the site deployed etc, above the wee more box on the right.
4) Have a 'Related Templates' carousel at the bottom of the page. 
5) Setup the Examples on a Live server somewhere, I am sorely tempted to dockerise this, since it would allow us to get the sites up and deployed and side step the codesandboxes for the time-being until support for that bears better fruits...
6) Once the Sites are setup, screenshot and setup a lighthouse API on the example page to reflect the lighthouse scores - No Puppetter, I have earmarked that 11ty screenshot tool that @jasikpark mentioned in the previous PR,
For the lighthouse API I was going to place this inside a React component to fetch the data on page load. 

This is just an initial concept, slightly better than v1, however any guidance and advice would be greatly appreciated.

### CODE REVIEW

**Comment by FredKSchott** [comment]
Looking forward to trying this out! @aFuzzyBear looks like build failed with this error: `Not Found (/_astro/src/components/Examples/Functions/generate-hero-img.js)`

**Comment by aFuzzyBear** [comment]
ah my bad i was doing some house keeping ill have that fixed in this next commit boss 2 mins

**Comment by FredKSchott** [comment]
awesome, no rush!

**Comment by aFuzzyBear** [comment]
That should be it working now @FredKSchott , I appreciate you taking a look at this, 
Firstly my apologies about the time its taken, this month has been a bit hectic. I had made several different styles of getting the cards for each template to have the right look to it, Caleb has pointed me in the way of these neurophic cards and I kinda went with these 'space pods' looking cards.
The background Images, or Hero Images, are just place holders, I need to source better images for these, had ran my own optimiser over the top just to reduce the size and well the quality is a bit to be desired.
With the thumbnails, I did manage to find a icon pack that served the purpose, however I do have an idea for the Frameworks icons, so bear with me on that one...
With the pods, I wanted each to have the necessary UI to get going, and explore that codebase, working closely with Sarah, we managed to get codesandbox and github.dev and github.com to work, the next step in this development is to have a live site for each template in the wild, there is a few benefits that this would bring. I could take a live pic of the site, and display that on templates page, (this is a WIP), having a permalink to a live site would be alot easier to maintain, also having a container for each template would be handy, the blog template page is a good example of what I was wanting to do with that, minus the dockerfile.
With the github.dev there is the added ability of having Code Tours setup, I have yet to implement this as I need this to be merged into the main branch then be up-todate with the templates to then write up on the CodeTours, but that is a seperate PR which would I would like to discuss with you in the future. 
Still going to work on this wee project, I did want some feedback as in the terms of direction and how it looks, if it is okay etc.

**Comment by aFuzzyBear** [comment]
@FredKSchott, that this ready for you to take a look at dude,

**Comment by jasikpark** [comment]
I tried to take a look, but I'm getting 404s from Vercel D:

**Comment by aFuzzyBear** [comment]
> I tried to take a look, but I'm getting 404s from Vercel D:

yeh dude i dont know why that is happening 😓 gots a feeling ive done something wrong here,

**Comment by FredKSchott** [comment]
Ah, I'm surprised that this didn't error in Vercel, but I see this error in the logs:

```
(node:1028) UnhandledPromiseRejectionWarning: Error: Invalid route src/pages/$example.astro — Astro's Collections API has been replaced by dynamic route params.
--
00:56:09.775 | at file:///vercel/path0/packages/astro/dist/manifest/create.js:28:15
00:56:09.775 | at Array.forEach (<anonymous>)
00:56:09.775 | at walk (file:///vercel/path0/packages/astro/dist/manifest/create.js:11:25)
00:56:09.775 | at createManifest (file:///vercel/path0/packages/astro/dist/manifest/create.js:103:3)
00:56:09.775 | at createRuntime (file:///vercel/path0/packages/astro/dist/runtime.js:309:15)
00:56:09.775 | at async build (file:///vercel/path0/packages/astro/dist/build.js:40:24)
00:56:09.776 | at async buildAndExit (file:///vercel/path0/packages/astro/dist/cli.js:11:15)


```

Sounds like you'll need to update this to run on Astro latest.

**Comment by aFuzzyBear** [comment]
ah.... I'll get that changed over,

**Comment by FredKSchott** [comment]
awesome! If you can get it running again I'll take a look at the code

**Comment by FredKSchott** [comment]
Yup, and move from `createCollection` to `getStaticPaths` 
https://docs.astro.build/reference/api-reference#getstaticpaths

**Comment by aFuzzyBear** [comment]
Im having a bit of difficulty getting the dynamic routes working atm, i will keep bashing at this, over the next couple of days (time permitting), sorry,

**Comment by aFuzzyBear** [comment]
@FredKSchott, this should be working now, however it is failing in the deployment of the docs, and idk why,

**Comment by FredKSchott** [comment]
Okay, I was finally able to check this out! There was a lot of great stuff here, I especially love the attention to detail with the different icons and background images.

Unfortunately, there was almost TOO much stuff here to review, and definitely too much to merge directly. The build wasn't running, there were ~140 files in the diff, and there was so much code it was hard to tell what was meant to be merged and what was outdated / safe to delete (ex: `examples.astro`, `themes-and-examples.astro`, `demo.astro`, etc. etc.)

instead of going through a bunch more back and forth on this, I took just the smallest "examples" page that I could and merged that (now called "themes"). I wasn't able to use most of your code, but hopefully this gives us the foundation to improve on. 

In the future, we definitely won't be able to review a PR of this size again. This took me quite a bit of time to check out and trim down myself, and normally a PR reviewer won't have time to do that. I'd strongly recommend chatting through any future changes ahead of time on Discord to make sure that they're reasonably sized before starting.

Thanks again for pushing this forward! We'll also want to get some design eyes on this, once @natemoo-re is back from vacation

**Comment by FredKSchott** [comment]
Merged and now available on next: https://next.docs.astro.build/themes

**Comment by aFuzzyBear** [comment]
It was a fun wee project to do, sorry it went too big, I could minimise it, given the amount of changes that were made I totally see what you meant. Caleb did advise me earlier on about not making the pr too big, i should of heeded his advice, however I just wanted to get this done, and at the time I thought it would of been safer to have it under the one branch. Ill learn for the next time. 

Thanks for taking a look over it, kinda gutted that it didn't make the mark,

**Comment by aFuzzyBear** [comment]
What if I made a better PR with only the final changes added to it, it should reduce the size of the merger by a phenomenal amount, and it could be sat to the side for the time being, I appreciate that you guys are extremely busy, and really didnt wish for this to be too time consuming. Personally I would like to keep pushing with this, for the only reason that it is giving me the challenges to learn Astro better. Alot better than I would of learnt had I been left to my own devices. With that being said, I will make the PR's shorter and more concise to prevent the mistakes from this one being repeated again. 

Your 'Themes' page was something that I was thinking alot about the past few days, whereas I had a content-less section for the Community Templates, I was wanting to expand that out and introduce Sanders community showcase, but now you have given me the idea of adding in Community Packages to the mix. 

That is if you don't mind me indulging in this further,

**Comment by FredKSchott** [comment]
No worries, and don’t beat yourself up about it! This page probably wouldn’t even exist without your work pushing to make it happen, so overall this is still great work that is very much appreciated.

I only harp on it because I knew Caleb had tried to give that feedback as well, and it’s something that’s pretty easily fixed next time with a bit more discussion at the start. 

If you’re still interested in improving on this now that it’s merged, let’s spin up a thread on discord to come up with a plan for the next PR before starting!

**Pull request closed without merging**
