### PR TITLE
[i18n][Docs] Change some Spanish translations for Getting Started page

### PR DESCRIPTION
**Pull request by kcmr**
## Changes

- Replaces some words that have the same literal translation but are used for different cases.
- Some words are not translated because they are better understood in English for technical docs (template instead of modelo).
- Uses second person of singular (tú) more consistently.
- Minor fixes.

## Testing

No tests were written.

## Docs

Getting Started page for Spanish was updated.

### CODE REVIEW

**Comment by kcmr** [comment]
Hi! Not sure if changeset should be updated. Please, let me know if you don't want it.

**Comment by jgil-r** [comment]
I don't think you need add a changeset for this. Changes look good though. I wonder how we can keep these Spanish translations more consistent. I'm sure there are many differences between Spanish in Spain compared to Mexico for example.

**Comment by FredKSchott** [comment]
LGTM! Open to any ideas, but I do not think it is feasible to maintain both regional translations of Spanish separately. I wonder how other projects handle this. Do they just choose one and stick with it? Or maybe try to avoid region-specific wording?

**Comment by kcmr** [comment]
> LGTM! Open to any ideas, but I do not think it is feasible to maintain both regional translations of Spanish separately. I wonder how other projects handle this. Do they just choose one and stick with it? Or maybe try to avoid region-specific wording?

Looking at React docs, it seems that they only have one Spanish version that uses the same style followed here (second person of singular). I've never read the React documentation in Spanish before, but it sounds quite neutral to me.

Thank you for merging :)

**Pull request merged**
