### PR TITLE
📘 DOC: Add DuckDuckGo-based static form search

### PR DESCRIPTION
**Pull request by jasikpark**
## Docs

Adds a DuckDuckGo form with `site:docs.astro.build` to the header of the docs site, so that people can more easily navigate the docs until we have algolia.

### CODE REVIEW

**Comment by FredKSchott** [comment]
Nice! I'm still trying to get Agolia hooked up, but ran into a weird renderer issue with running both React & Preact renderers so I had to stop for the night: astro-docs-qfneu4kkw-pikapkg.vercel.app

I'm +1 to merging this PR, if you can figure out mobile styles as well. Then, I can rebase my branch on top of yours and build on top of that.

I think my styling has a bit more polish, if you want to grab my CSS now to use in your PR.

**Comment by jasikpark** [comment]
That link doesn't work for me 🤔 it wants me to sign into Vercel.. I'll check out your branch later though and see about updating the styles

**Comment by FredKSchott** [comment]
@jasikpark I think #917 is close to merge-ready with mobile styles working, okay to close this in favor of that one?

**Comment by jasikpark** [comment]
@FredKSchott could you pull my header button styles from this into that one? I suppose I could just make a separate PR for the fix as well though...

**Comment by jasikpark** [comment]
Currently testing whether I can just cherrypick the styles..

**Comment by jasikpark** [comment]
It looks like it doesn't work perfectly, but I was trying to fix the hover+focus-visible+active styles for the menu toggle, since they no longer work

**Pull request closed without merging**
