### PR TITLE
Add remark-slug

### LINKED ISSUE #805: 🐛 BUG: Remark should generate unique header id's
### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

When you have two sections with the same titles, they get the same element id, but that is not permitted in HTML and also breaks links as well.

This also breaks the table of content links on the docs site.

### Steps to Reproduce

1. Look at the header id's at https://docs.astro.build/comparing-astro-vs-other-tools

### Link to Minimal Reproducible Example (Optional)

_No response_

### PR DESCRIPTION
**Pull request by mmarkelov**
## Changes

Added [remark-slug](https://github.com/remarkjs/remark-slug) to fix #805

### CODE REVIEW

**Comment by mmarkelov** [comment]
@jasikpark for sure. But idk the best place to add this information.

**Comment by matthewp** [comment]
@mmarkelov Here: https://docs.astro.build/guides/markdown-content#remark-and-rehype-plugins which is here: https://github.com/snowpackjs/astro/blob/main/docs/src/pages/guides/markdown-content.md

**Comment by matthewp** [comment]
@mmarkelov can you add a changeset? Running `yarn changeset` and walk through the questions. This should be a `patch` change (it's a non-breaking change < 1.0 so not minor).

**Comment by matthewp** [comment]
bump @mmarkelov

**Comment by mmarkelov** [comment]
@matthewp added. Sorry for late response. didn't notice your comment

**Review by jasikpark — APPROVED** [review]
LGTM!

**Pull request merged**
