### PR TITLE
Expose `content.astro.html` to `Astro.fetchContent`

### LINKED ISSUE #571: 💡 Expose rendered `html` when using `Astro.fetchContent`
### Motivation

We've had quite a number of people ask how to get the rendered HTML from a post pulled in using `Astro.fetchContent`.

### Proposed Solution

On the returned posts, we already have the `astro` metadata which includes `headers` and the raw `source`.

### Alternatives considered

Is `rendered` a better name than `html`? 

### Risks, downsides, and/or tradeoffs

No risks I can see of, we already allow this if you pipe `astro.source` to `<Markdown>`, it's just an annoying extra step.

### Detailed Design

_No response_

### Open Questions

_No response_

### Help make it happen!

- [X] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

### PR DESCRIPTION
**Pull request by natemoo-re**
## Changes

Adds `astro.html` to results returned by `Astro.fetchContent`. Closes #571.

> **Note** there was a performance concern to rendering all `.md` files fetched with `Astro.fetchContent`, but it turns out we were already rendering them completely! This just exposes the result under the `astro.html` key.

## Testing

No tests, just exposing another prop.

## Docs

- [x] TODO: add docs

### CODE REVIEW

**Comment by matthewp** [comment]
Can you document this?

**Comment by natemoo-re** [comment]
@matthewp added a note to the docs!

**Comment by natemoo-re** [comment]
@matthewp good to merge?

**Comment by matthewp** [comment]
@natemoo-re lgtm

**Pull request merged**
