### PR TITLE
Docs/add section tracking in toc

### PR DESCRIPTION
**Pull request by jasikpark**
## Docs

I'm trying to setup a way to track what section of the document you are in, using prior art from https://benfrain.com/building-a-table-of-contents-with-active-indicator-using-javascript-intersection-observers/ and https://www.emgoto.com/react-table-of-contents/, but it's a bit buggy right now :/ the second commit just trackers the headers and works well, other than the fact that if you scroll up it doesn't select the previous section.

### CODE REVIEW

**Comment by aFuzzyBear** [comment]
hey dude, great attempt at this, bit buggy tho, it only highlights the text that enters the viewport not those elements that are in the center of the viewport, =(
but this is what the sidebar should be like imo, where you scroll and the text is in the center it should be active, jumping between the sections.

**Comment by tony-sull** [comment]
If I remember right the IntersectionObserver callback only returns elements that reported an update.  Meaning if section A was already on screen when section B scrolls into view, the callback will only give the section B element.

It looks like the callback may be replacing all active headers with `setActiveHeadings`.  Any chance it just needs an update to merge the updated sections' active state with the unchanged sections already stored in state?

**Comment by jasikpark** [comment]
I figured it might work best to have "activeSections" for all active sections that are visible, with a gradient effect (not currently implemented) for how much they were in the center of the page..

**Comment by jasikpark** [comment]
> If I remember right the IntersectionObserver callback only returns elements that reported an update.  Meaning if section A was already on screen when section B scrolls into view, the callback will only give the section B element.
> 
> 
> 
> It looks like the callback may be replacing all active headers with `setActiveHeadings`.  Any chance it just needs an update to merge the updated sections' active state with the unchanged sections already stored in state?

That's a good point! I'll try that.

**Comment by natemoo-re** [comment]
@jasikpark Still looks a bit buggy. Let me know if I can help on this one, it's a tough one to get right.

An alternative approach I've seen is to track the position of the headings with `getBoundingClientRect()` (updating on `resize`) and `window.scrollY` (updating passively on `scroll`). There are some performance gotchas to be careful with but it's less likely to give false positives than the `IntersectionObserver` approach.

**Comment by jasikpark** [comment]
:D it looks like I got it sorted out, thanks to following <https://jvns.ca>'s recommendation to start from where you *know* things work, and shmoove from there!

**Comment by FredKSchott** [comment]
Looks really smooth, but getting some odd behavior. I'd expect only one to be highlighted this way: 
Screen Shot 2021-08-16 at 9 28 32 PM

One thing that I might suggest: if you're starting to go the route of "multiple can be highlighted at once" I think that really clashes with how people see an "active" link. In that case, I'd reccomend going a more subtle route and making the left-side bar colored instead. Something like:
Screen Shot 2021-08-16 at 9 31 06 PM

**Comment by jasikpark** [comment]
ooh that's an interesting option! i'll play around with A. selecting a heading as *the* section you're reading + move the multiple section display to the sidebar like you said - that makes sense to me

**Comment by FredKSchott** [comment]
Still strange! 😆

Screen Shot 2021-08-18 at 6 17 36 PM

**Comment by okikio** [comment]
Is this still WIP?

**Comment by jasikpark** [comment]
> Is this still WIP?

Yep, though I've ignored it for a little bit 😅 - I need to sort it out...

**Comment by FredKSchott** [comment]
Still not working: 
Screen Shot 2021-09-06 at 4 46 40 PM

If it helps, I'm happy with the way it is currently and don't have any strong feeling about seeing this merged. At any rate, this is probably lower priority compared to prettier IMO.

**Comment by jasikpark** [comment]
> Still not working:
> Screen Shot 2021-09-06 at 4 46 40 PM
> 
> If it helps, I'm happy with the way it is currently and don't have any strong feeling about seeing this merged. At any rate, this is probably lower priority compared to prettier IMO.

To explain the current behavior, it's working as I intended, where each section that you're currently  in is highlighted, depending on heading.

**Comment by FredKSchott** [comment]
"Overview" and "Learn Astro" are still highlighted though, which aren't anywhere on the page. That's my bad, I should have called that out with the screenshot to make my comment clear

**Comment by FredKSchott** [comment]
Closing as not yet ready, but feel free to open again when it's ready!

**Comment by FredKSchott** [comment]
Also, if it matters: I don't mind the current behavior without this and I hear so many people in the community asking for Prettier support. If you only had the time to work on one of the two, I'd strongly encourage the prettier work!

**Pull request closed without merging**
