### PR TITLE
CodeSandbox-izing via template override

### PR DESCRIPTION
**Pull request by sarah11918**
CodeSandbox doesn't recognize astro starter repos as node projects, and overriding this in a sandbox.config should fix that.

### CODE REVIEW

**Comment by jasikpark** [comment]
why not add this to all of the starters? i suppose `quick-start` is most likely to be used on codesandbox?

**Comment by sarah11918** [comment]
That's the plan, to add it to all the examples. I'm at least starting with the quick starter to try to get it successfully working as an initial test. (May turn out to need some extra stuff in config, too; I'll figure it out from this one.)

**Comment by FredKSchott** [comment]
just curious, do you know why CodeSandbox doesn't recognize Astro as a node project? Is this something we could ask them to fix on their end?

**Comment by sarah11918** [comment]
They do mention that this (link below) is the logic they use to determine an imported repo's template:

https://github.com/codesandbox/codesandbox-importers/blob/master/packages/import-utils/src/create-sandbox/templates.ts#L63

So yes, I suppose this matter could be fixed the other way 'round, by asking them to update their logic.  :)

**Comment by FredKSchott** [comment]
Any interest in creating a PR with them to see how quickly they might update? I think it would be as simple as this change to that file:

```diff
  if (totalDependencies.indexOf("vite") > -1) {
    return "node";
  }
  
+  if (totalDependencies.indexOf("astro") > -1) {
+    return "node";
+  }
```

**Comment by sarah11918** [comment]
Drunk with power now that I can apparently create pull requests, I have done so:  

https://github.com/codesandbox/codesandbox-importers/pull/138

I noticed there's another open pull request for Feathers JS that's pretty much the same thing.  :)

(If it's accepted here in the meantime, even if only to reverse course and delete later, then I can do more on our FuzzyBear's starter kit work. But that's your call. 

Because, reasons, I think I need the original repo on Github to have the codebox config file upon original import in order to properly get the starter repo to build. I don't seem to have a good way, even after forking and adding the config myself, of getting CodeSandbox to "re-imagine" the project as node.)

**Comment by FredKSchott** [comment]
Awesome, thanks! I'm okay with merging this in starter for now, and then revisiting next week based on whether there's any action on that PR or not

**Pull request merged**
