### PR TITLE
Doc's `v0.21` Prep

### PR DESCRIPTION
**Pull request by aFuzzyBear**
##  Purpose

Seeking to provide a branch from the current doc's to allow for information pertaining to the anticipated release of Astro `v0.21`, to be compiled and collated. 

It would also allow for collaboration between those with invested effort into the Astro documentation to create the content needed to communicate the new changes to the community. 

Since the announcement of the new feature changes to astro in the coming release, there is a larger interest in the project. As a result their would inevitably be information leaking or in a better sense contaminating the current documentation site which would as of the new release be obsolete. 

It would make sense therefore to provide a new staging post for all new amendments and additions to be made to a separate branch, form which can be merged and replace the current documentation with the new one once the time comes.

### CODE REVIEW

**Comment by jonathantneal** [comment]
Now that #1406 has been merged, we can resume on this!

**Comment by jonathantneal** [comment]
Hey @aFuzzyBear, now that the docs are updated to v0.21, what would you like to see in this PR? Or do you think we should close it in favor of individual PRs to update specific sections or pages of the docs and v0.21 migration guide?

**Comment by natemoo-re** [comment]
@jonathantneal IMO this PR should be closed in favor of individual PRs to update our docs.

Apologies to @aFuzzyBear, we kind of dropped the ball on this to the point where this PR isn't super useful anymore.

**Comment by aFuzzyBear** [comment]
No worries at all guys, I'm working on a version controlled, internationalised version of the docs site on my local machine atm, once its somewhere working ill post a link to it so you guys can check it out. 
By the time I had stripped the docs out of the pages directory I had a lot of file changes that were needing to register and the first pr would of been massive 😅

**Pull request closed without merging**
