### PR TITLE
Add `with-vite-plugin-pwa` example

### PR DESCRIPTION
**Pull request by natemoo-re**
## Changes

- Adds built-in support for [`vite-plugin-pwa`](https://vite-plugin-pwa.netlify.app/).
- Does not add a dependency on `vite-plugin-pwa`, just adds a handler to call it after `astro build` if it exists.
- The user is still responsible for configuring and implementing the SW handling.

## Testing

Added an example

## Docs

No, but it should be before merge.

### CODE REVIEW

**Comment by matthewp** [comment]
Can you explain why we need special code for this plugin? Looking at their examples I don't see them calling this function manually. Why is it needed in this case? https://github.com/antfu/vite-plugin-pwa/tree/main/examples

**Comment by natemoo-re** [comment]
@matthewp Great question! I was following [these steps](https://vite-plugin-pwa.netlify.app/frameworks/vitepress.html#build) outlined for VitePress assuming that it wouldn't work the normal way in Astro. But now that I think about it, I didn't actually try _without_ doing this extra step. I'll double check that it's necessary.

**Comment by natemoo-re** [comment]
@matthewp turns out, we don't! This PR now just adds an example to our examples directory.

**Comment by matthewp** [comment]
@natemoo-re you probably just need to rebase to get this passing

**Pull request merged**
