### PR TITLE
Fix README header aspect ratio

### PR DESCRIPTION
**Pull request by dcastil**
## Changes

Just fixing the README header:

1. Preserves aspect ratio on mobile.
2. Header is served from same branch. If image gets changed in a branch, the header in that branch gets updated, too.

## Testing

| Before | After |
| --- | --- |
| IMG_A04ADB39D28C-1 | IMG_5A2E805D6A76-1 |

## Docs

No docs changed

### CODE REVIEW

**Review by natemoo-re — CHANGES_REQUESTED** [review]
Using the full URL was intentional, that allows it to display properly when the README is embedded on external sites like [NPM](https://www.npmjs.com/package/astro). Would you mind updating the URL?

I'm alright with removing the `width` and `height` since it is causing issues on mobile. I was under the impression that it's best practice to define the `width` and `height` so that the browser can reserve the correct space (and aspect ratio) before the image loads. Since we can't control how images are displayed with CSS, that's probably causing the stretching issue.

**Comment by dcastil** [comment]
@natemoo-re Thanks for the heads up. Hmmm that's tricky. I tried `width="100%" height="50%"`. Height of 50% in this case should be computed as 50% of its width. That should give the browser the ability to reserve the appropriate space but still scale it up and down as necessary. At least I hope so. 🤔

**Review by natemoo-re — APPROVED** [review]
Looks good! I removed the `width` and `height` since it wasn't doing what was expected. Better to just let the browser do its thing, I think.

**Comment by dcastil** [comment]
Just tested it and it doesn't reserve the appropriate space unfortunately. 😔

Screenshot 2021-06-17 at 18 08 21

But for some reason Lighthose still says there is 0 cumulative layout shifts.

**Comment by dcastil** [comment]
Ah you were faster than me! Anyway, thanks for the quick fix!

**Pull request merged**
