### PR TITLE
Bold props interface words

### LINKED ISSUE #1070: 📘 DOC: Make “Props interface typechecking” more obviously unimplemented in docs
There's quite a few people who don't notice that the Props interface for Astro component typechecking isn't yet implemented. Could we bold that section?

### PR DESCRIPTION
**Pull request by MarcusOtter**
## Changes
- What does this change?
  ~~Bolds some words because a few people (me included) have missed these words 😄~~
  Makes a paragraph in the docs into a blockquote and makes "In the future" **_Bold and Italic_**

Closes #1070 

## Testing
Tested locally

## Docs
Yes

### CODE REVIEW

**Comment by jasikpark** [comment]
Thanks for making this PR! I think it might work best to italicize the entire sentence? 

link to the changed sentence:
https://astro-docs-git-fork-marcusotter-docs-bold-word-pikapkg.vercel.app/core-concepts/astro-components#component-props

image

**Comment by jasikpark** [comment]
Though maybe that's just a case where our bold weight needs to be more bold, actually 😅

**Comment by MarcusOtter** [comment]
Yeah didn't do much of a change 😄 How about _**Bold italic**_ to really get the point across?

**Comment by FredKSchott** [comment]
Happy with anything here! FYI this will go out tomorrow when we release our `main` branch to `npm install astro` and cut `v0.19.0`.

**Comment by drwpow** [comment]
I’m fine with any change here, but I think that we probably need more of a [callout](https://docs.gitbook.com/editing-content/markdown#hints-and-callouts) block that more explicitly highlights a future deprecation, or a coming soon feature like here.

**Comment by MarcusOtter** [comment]
I agree with @drwpow. It seems like `blockquote`s are currently used for this (a bit semantically incorrect but I understand that there aren't a lot of good alternatives in markdown).

Example:
image

Should I convert this paragraph to a blockquote?

**Comment by MarcusOtter** [comment]
I did.
| Before | After |
| ------ | ----- |
| image | image |

**Comment by FredKSchott** [comment]
LGTM! This will go out tomorrow when we release v0.19.0

**Pull request merged**
